// =================================================================================
// 📚 雅思單字資料庫 - C 完整重製版 (Complete & High Quality C-List)
// =================================================================================
// 範圍：Caffeine (咖啡因) ~ Cynical (憤世嫉俗的)
// 品質保證：所有例句均已升級為雅思 Band 7+ 學術語境，包含多重詞性拆分。
// 使用方式：在 index.html 中加入 <script src="vocab_c.js"></script>

window.VOCAB_LIBRARY = window.VOCAB_LIBRARY || [];
window.VOCAB_LIBRARY = window.VOCAB_LIBRARY.concat([
    // --- C1: Caffeine to Civic ---
    { id: "c001", word: "Caffeine", ipa: "/ˈkæf.iːn/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "咖啡因", def_en: "a stimulant found in coffee, tea, and chocolate", sentence: "Excessive caffeine consumption has been linked to sleep disturbances and heightened anxiety levels in adolescents.", sentence_trans: "過量攝取咖啡因已被證實與青少年的睡眠障礙及焦慮水平升高有關。", synonyms: ["stimulant"], phrases: ["caffeine intake"] }] }] },
    { id: "c002", word: "Calcium", ipa: "/ˈkæl.si.əm/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "鈣", def_en: "a chemical element essential for healthy bones", sentence: "A diet deficient in calcium can predispose individuals to osteoporosis later in life.", sentence_trans: "飲食中缺乏鈣質可能導致個體在晚年易患骨質疏鬆症。", synonyms: [], phrases: ["calcium deficiency"] }] }] },
    { id: "c003", word: "Calculator", ipa: "/ˈkæl.kjə.leɪ.tər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "計算機", def_en: "a device used for making mathematical calculations", sentence: "While calculators are permitted in some modules, students are encouraged to develop strong mental arithmetic skills.", sentence_trans: "雖然某些模組允許使用計算機，但仍鼓勵學生培養強大的心算能力。", synonyms: [], phrases: [] }] }] },
    { id: "c004", word: "Calligraphy", ipa: "/kəˈlɪɡ.rə.fi/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "書法", def_en: "decorative handwriting", sentence: "Traditional Chinese calligraphy is revered not merely as a form of writing, but as a high visual art reflecting the artist's character.", sentence_trans: "中國傳統書法不僅被視為一種書寫形式，更被尊崇為反映藝術家品格的高級視覺藝術。", synonyms: ["penmanship"], phrases: [] }] }] },
    { id: "c005", word: "Canal", ipa: "/kəˈnæl/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "運河", def_en: "an artificial waterway", sentence: "The construction of the Panama Canal significantly reduced maritime travel time between the Atlantic and Pacific Oceans.", sentence_trans: "巴拿馬運河的建設顯著縮短了大西洋和太平洋之間的海上航行時間。", synonyms: ["waterway", "channel"], phrases: ["shipping canal"] }] }] },
    { id: "c006", word: "Canvas", ipa: "/ˈkæn.vəs/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "帆布；畫布", def_en: "strong cloth used for painting", sentence: "The political turmoil of the era provided a broad canvas for the novelist to explore themes of loyalty and betrayal.", sentence_trans: "那個時代的政治動盪為這位小說家提供了一個廣闊的畫布，以探索忠誠與背叛的主題。", synonyms: ["fabric"], phrases: ["blank canvas"] }] }] },
    { id: "c007", word: "Capability", ipa: "/ˌkeɪ.pəˈbɪl.ə.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "能力；性能", def_en: "the power or ability to do something", sentence: "The new defense system has the capability to intercept missiles with unprecedented accuracy.", sentence_trans: "新的防禦系統有能力以前所未有的精確度攔截導彈。", synonyms: ["ability", "capacity", "competence"], phrases: ["military capability"] }] }] },
    { id: "c008", word: "Cape", ipa: "/keɪp/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "海角；披肩", def_en: "a headland", sentence: "Navigating around the cape was notoriously dangerous for 18th-century sailors due to unpredictable storms.", sentence_trans: "由於不可預測的風暴，繞過該海角航行對18世紀的水手來說是出了名的危險。", synonyms: ["headland", "promontory"], phrases: [] }] }] },
    { id: "c009", word: "Capsule", ipa: "/ˈkæp.sjuːl/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "膠囊；太空艙", def_en: "a small case or container", sentence: "The medication is encapsulated in a gelatin shell to ensure it dissolves in the intestine rather than the stomach.", sentence_trans: "藥物被封裝在明膠殼中，以確保其在腸道而非胃中溶解。", synonyms: ["pill", "pod"], phrases: ["time capsule"] }] }] },
    { id: "c010", word: "Caption", ipa: "/ˈkæp.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "標題；說明文字", def_en: "a title or explanation appended to an illustration", sentence: "The caption beneath the photograph provided essential context regarding the historical event.", sentence_trans: "照片下方的說明文字提供了關於該歷史事件的必要背景。", synonyms: ["title", "heading"], phrases: [] }] }] },
    { id: "c011", word: "Captive", ipa: "/ˈkæp.tɪv/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "被俘的；受限制的", def_en: "imprisoned or confined", sentence: "Zoos are increasingly focusing on breeding programs for captive species that are extinct in the wild.", sentence_trans: "動物園正日益關注那些在野外已滅絕的圈養物種的繁殖計畫。", synonyms: ["confined", "imprisoned"], phrases: ["captive audience"] }] }, { pos: "n.", items: [{ def_zh: "俘虜", def_en: "a prisoner", sentence: "The hostages were held as captives for three months before negotiations secured their release.", sentence_trans: "人質被當作俘虜關押了三個月，談判才確保了他們的獲釋。", synonyms: ["prisoner", "hostage"], phrases: [] }] }] },
    { id: "c012", word: "Captivity", ipa: "/kæpˈtɪv.ə.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "囚禁；圈養", def_en: "the condition of being imprisoned", sentence: "Many marine biologists argue that cetaceans suffer psychological distress when kept in captivity for entertainment.", sentence_trans: "許多海洋生物學家認為，鯨豚類動物在被圈養以供娛樂時會遭受心理痛苦。", synonyms: ["confinement", "detention"], phrases: ["bred in captivity"] }] }] },
    { id: "c013", word: "Carbon", ipa: "/ˈkɑː.bən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "碳", def_en: "a chemical element", sentence: "International treaties aim to drastically reduce carbon emissions to mitigate the catastrophic effects of global warming.", sentence_trans: "國際條約旨在大幅減少碳排放，以緩解全球暖化的災難性影響。", synonyms: [], phrases: ["carbon footprint", "carbon dioxide"] }] }] },
    { id: "c014", word: "Cardboard", ipa: "/ˈkɑːd.bɔːd/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "硬紙板", def_en: "stiff paper used for boxes", sentence: "The homeless shelter distributed cardboard boxes to provide temporary insulation against the freezing ground.", sentence_trans: "遊民收容所分發硬紙箱，以提供針對冰凍地面的臨時隔絕。", synonyms: [], phrases: [] }] }] },
    { id: "c015", word: "Cardinal", ipa: "/ˈkɑː.dɪ.nəl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "基本的；主要的", def_en: "of the greatest importance", sentence: "Respect for individual autonomy is a cardinal principle of modern medical ethics.", sentence_trans: "尊重個人自主權是現代醫學倫理的一項基本原則。", synonyms: ["fundamental", "primary", "paramount"], phrases: ["cardinal rule"] }] }] },
    { id: "c016", word: "Carefree", ipa: "/ˈkeə.friː/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "無憂無慮的", def_en: "free from anxiety or responsibility", sentence: "His carefree attitude towards his academic studies resulted in poor performance during the final examinations.", sentence_trans: "他對學業無憂無慮的態度導致了期末考試的糟糕表現。", synonyms: ["untroubled", "easygoing"], phrases: [] }] }] },
    { id: "c017", word: "Caretaker", ipa: "/ˈkeəˌteɪ.kər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "管理員；看守政府", def_en: "a person employed to look after a building or person", sentence: "The caretaker government will oversee the country's affairs until the general election is held next month.", sentence_trans: "看守政府將監督國家事務，直到下個月舉行大選。", synonyms: ["janitor", "warden"], phrases: ["caretaker government"] }] }] },
    { id: "c018", word: "Carnival", ipa: "/ˈkɑː.nɪ.vəl/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "嘉年華；狂歡節", def_en: "a period of public revelry", sentence: "The annual carnival serves as a significant tourist attraction, boosting the local economy by millions of dollars.", sentence_trans: "年度嘉年華作為重要的旅遊景點，為當地經濟帶來了數百萬美元的增長。", synonyms: ["festival", "fiesta"], phrases: [] }] }] },
    { id: "c019", word: "Carton", ipa: "/ˈkɑː.tən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "紙盒", def_en: "a light box or container", sentence: "Recycling a carton requires less energy than producing a new one from raw materials.", sentence_trans: "回收紙盒所需的能量少於從原材料生產新紙盒。", synonyms: ["box", "container"], phrases: ["milk carton"] }] }] },
    { id: "c020", word: "Cashier", ipa: "/kæˈʃɪər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "收銀員；出納員", def_en: "a person handling payments", sentence: "The bank cashier was trained to detect counterfeit currency using UV light.", sentence_trans: "銀行出納員受過訓練，使用紫外線檢測偽鈔。", synonyms: ["teller", "clerk"], phrases: [] }] }] },
    { id: "c021", word: "Casino", ipa: "/kəˈsiː.nəʊ/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "賭場", def_en: "a public room for gambling", sentence: "The proliferation of online casinos has raised serious concerns about gambling addiction among the youth.", sentence_trans: "線上賭場的激增引發了對青少年賭博成癮的嚴重擔憂。", synonyms: [], phrases: [] }] }] },
    { id: "c022", word: "Casualty", ipa: "/ˈkæʒ.ju.əl.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "傷亡人員；受害者", def_en: "a person killed or injured in a war or accident", sentence: "Civilian casualties in the conflict have drawn international condemnation and calls for a ceasefire.", sentence_trans: "衝突中的平民傷亡引起了國際社會的譴責和停火呼籲。", synonyms: ["victim", "fatality"], phrases: ["heavy casualties"] }] }] },
    { id: "c023", word: "Catastrophe", ipa: "/kəˈtæs.trə.fi/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "大災難", def_en: "an event causing great and often sudden damage", sentence: "Failure to address climate change swiftly could lead to a global environmental catastrophe.", sentence_trans: "未能迅速解決氣候變遷問題可能導致全球環境災難。", synonyms: ["disaster", "calamity"], phrases: ["financial catastrophe"] }] }] },
    { id: "c024", word: "Categorize", ipa: "/ˈkæt.ə.ɡər.aɪz/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "分類", def_en: "place in a particular class or group", sentence: "Biologists categorize organisms based on their genetic and physical characteristics.", sentence_trans: "生物學家根據生物的遺傳和物理特徵對其進行分類。", synonyms: ["classify", "group", "sort"], phrases: [] }] }] },
    { id: "c025", word: "Cater", ipa: "/ˈkeɪ.tər/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "迎合；提供飲食", def_en: "provide food and drink; try to satisfy a need", sentence: "The curriculum is specifically designed to cater to students with diverse learning needs.", sentence_trans: "該課程專為迎合具有不同學習需求的學生而設計。", synonyms: ["serve", "accommodate"], phrases: ["cater to", "catering service"] }] }] },
    { id: "c026", word: "Caterpillar", ipa: "/ˈkæt.ə.pɪl.ər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "毛毛蟲", def_en: "the larva of a butterfly or moth", sentence: "The metamorphosis of a caterpillar into a butterfly is a fascinating biological process.", sentence_trans: "毛毛蟲變態為蝴蝶是一個迷人的生物過程。", synonyms: ["larva"], phrases: [] }] }] },
    { id: "c027", word: "Cathedral", ipa: "/kəˈθiː.drəl/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "大教堂", def_en: "the principal church of a diocese", sentence: "The Gothic cathedral stands as a testament to the architectural prowess of the Middle Ages.", sentence_trans: "這座哥德式大教堂是中世紀建築造詣的證明。", synonyms: ["church"], phrases: [] }] }] },
    { id: "c028", word: "Caution", ipa: "/ˈkɔː.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "謹慎", def_en: "care taken to avoid danger", sentence: "Investors are advised to exercise extreme caution when dealing with volatile cryptocurrency markets.", sentence_trans: "建議投資者在處理波動的加密貨幣市場時要格外謹慎。", synonyms: ["care", "prudence"], phrases: ["proceed with caution"] }] }, { pos: "v.", items: [{ def_zh: "警告", def_en: "warn", sentence: "The report cautions against making hasty decisions based on incomplete data.", sentence_trans: "該報告警告不要基於不完整的數據做出倉促決定。", synonyms: ["warn", "alert"], phrases: [] }] }] },
    { id: "c029", word: "Cautious", ipa: "/ˈkɔː.ʃəs/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "謹慎的", def_en: "careful to avoid potential problems", sentence: "The government has adopted a cautious approach to lifting the lockdown restrictions.", sentence_trans: "政府採取了謹慎的態度來解除封鎖限制。", synonyms: ["careful", "wary", "circumspect"], phrases: ["cautious optimism"] }] }] },
    { id: "c030", word: "Cavity", ipa: "/ˈkæv.ə.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "洞；蛀牙", def_en: "an empty space within a solid object; tooth decay", sentence: "Regular dental checkups are essential for detecting cavities before they become painful.", sentence_trans: "定期牙科檢查對於在蛀牙變痛之前發現它們至關重要。", synonyms: ["hole", "hollow"], phrases: ["chest cavity"] }] }] },
    { id: "c031", word: "Celebrity", ipa: "/səˈleb.rə.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "名人；名聲", def_en: "a famous person", sentence: "The obsession with celebrity culture can have negative impacts on adolescents' self-esteem.", sentence_trans: "對名人文化的痴迷可能會對青少年的自尊產生負面影響。", synonyms: ["star", "personality"], phrases: ["celebrity status"] }] }] },
    { id: "c032", word: "Celery", ipa: "/ˈsel.ər.i/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "芹菜", def_en: "a cultivated plant used as a vegetable", sentence: "Celery is often recommended in weight-loss diets due to its remarkably low calorie content.", sentence_trans: "芹菜因其極低的卡路里含量而常被推薦用於減肥飲食。", synonyms: [], phrases: [] }] }] },
    { id: "c033", word: "Cellular", ipa: "/ˈsel.jə.lər/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "細胞的；蜂窩式的", def_en: "relating to living cells", sentence: "Cellular respiration is the metabolic process by which cells generate energy from glucose.", sentence_trans: "細胞呼吸是細胞從葡萄糖產生能量的代謝過程。", synonyms: [], phrases: ["cellular level", "cellular phone"] }] }] },
    { id: "c034", word: "Celsius", ipa: "/ˈsel.si.əs/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "攝氏", def_en: "a scale of temperature", sentence: "Global temperatures are predicted to rise by two degrees Celsius if carbon emissions are not curbed.", sentence_trans: "如果不抑制碳排放，預計全球氣溫將上升攝氏兩度。", synonyms: ["centigrade"], phrases: [] }] }] },
    { id: "c035", word: "Cement", ipa: "/sɪˈment/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "鞏固；加強", def_en: "settle or establish firmly", sentence: "The bilateral trade agreement served to cement the diplomatic ties between the two nations.", sentence_trans: "該雙邊貿易協定有助於鞏固兩國之間的外交關係。", synonyms: ["strengthen", "solidify"], phrases: ["cement a relationship"] }] }, { pos: "n.", items: [{ def_zh: "水泥", def_en: "building material", sentence: "Cement production is a major contributor to industrial carbon dioxide emissions.", sentence_trans: "水泥生產是工業二氧化碳排放的主要貢獻者。", synonyms: [], phrases: [] }] }] },
    { id: "c036", word: "Cemetery", ipa: "/ˈsem.ə.tri/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "墓地", def_en: "a burial ground", sentence: "The historic cemetery contains the graves of many notable figures from the 19th century.", sentence_trans: "這座歷史悠久的墓地包含許多 19 世紀著名人物的墳墓。", synonyms: ["graveyard"], phrases: [] }] }] },
    { id: "c037", word: "Census", ipa: "/ˈsen.səs/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "人口普查", def_en: "an official count or survey of a population", sentence: "Census data is utilized by the government to allocate resources and plan infrastructure effectively.", sentence_trans: "政府利用人口普查數據來有效分配資源和規劃基礎設施。", synonyms: ["survey"], phrases: ["census bureau"] }] }] },
    { id: "c038", word: "Ceramic", ipa: "/səˈræm.ɪk/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "陶瓷的", def_en: "made of clay and hardened by heat", sentence: "Advanced ceramic materials are used in aerospace engineering due to their high heat resistance.", sentence_trans: "先進的陶瓷材料因其高耐熱性而被用於航空航天工程。", synonyms: ["pottery"], phrases: ["ceramic tiles"] }] }] },
    { id: "c039", word: "Ceremony", ipa: "/ˈser.ɪ.mə.ni/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "儀式；典禮", def_en: "a formal religious or public occasion", sentence: "The inauguration ceremony marks the formal beginning of the president's term in office.", sentence_trans: "就職典禮標誌著總統任期的正式開始。", synonyms: ["rite", "ritual"], phrases: ["awards ceremony"] }] }] },
    { id: "c040", word: "Certainty", ipa: "/ˈsɜː.tən.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "確定性", def_en: "firm conviction that something is the case", sentence: "In scientific research, absolute certainty is rare; theories are always subject to revision.", sentence_trans: "在科學研究中，絕對的確定性是罕見的；理論總是需要根據新證據進行修訂。", synonyms: ["assurance", "confidence"], phrases: ["with certainty"] }] }] },
    { id: "c041", word: "Certificate", ipa: "/səˈtɪf.ɪ.kət/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "證書", def_en: "an official document attesting a certain fact", sentence: "A medical certificate is required to substantiate your claim for extended sick leave.", sentence_trans: "需要醫療證明來證實您的長期病假申請。", synonyms: ["credential", "diploma"], phrases: ["birth certificate"] }] }] },
    { id: "c042", word: "Certify", ipa: "/ˈsɜː.tɪ.faɪ/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "證明；證實", def_en: "attest or confirm in a formal statement", sentence: "The auditor must certify that the company's financial accounts are accurate and compliant with regulations.", sentence_trans: "審計員必須證明公司的財務帳目是準確的且符合法規。", synonyms: ["verify", "validate"], phrases: ["certified public accountant"] }] }] },
    { id: "c043", word: "Chairperson", ipa: "/ˈtʃeəˌpɜː.sən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "主席", def_en: "a person chosen to preside over a meeting", sentence: "The chairperson facilitated the discussion, ensuring all committee members had a chance to speak.", sentence_trans: "主席推動了討論，確保所有委員會成員都有機會發言。", synonyms: ["chair", "president"], phrases: [] }] }] },
    { id: "c044", word: "Champagne", ipa: "/ʃæmˈpeɪn/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "香檳", def_en: "a white sparkling wine", sentence: "Champagne is traditionally served to toast significant achievements and corporate milestones.", sentence_trans: "傳統上會供應香檳來為重大成就和企業里程碑乾杯。", synonyms: [], phrases: [] }] }] },
    { id: "c045", word: "Chant", ipa: "/tʃɑːnt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "吟唱；反覆呼喊", def_en: "say or shout repeatedly in a sing-song tone", sentence: "The protesters began to chant slogans demanding immediate political reform.", sentence_trans: "抗議者開始高呼要求立即政治改革的口號。", synonyms: ["shout", "intone"], phrases: [] }] }] },
    { id: "c046", word: "Chaos", ipa: "/ˈkeɪ.ɒs/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "混亂", def_en: "complete disorder and confusion", sentence: "The sudden collapse of the banking system plunged the country into economic chaos.", sentence_trans: "銀行系統的突然崩潰使該國陷入經濟混亂。", synonyms: ["disorder", "turmoil", "anarchy"], phrases: ["descent into chaos"] }] }] },
    { id: "c047", word: "Chapel", ipa: "/ˈtʃæp.əl/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "小禮拜堂", def_en: "a small building for Christian worship", sentence: "The university campus includes a non-denominational chapel for student reflection and prayer.", sentence_trans: "大學校園包括一個供學生反思和祈禱的跨教派禮拜堂。", synonyms: ["shrine", "sanctuary"], phrases: [] }] }] },
    { id: "c048", word: "Characterize", ipa: "/ˈkær.ək.tə.raɪz/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "具有...特徵；描述...特性", def_en: "describe the distinctive nature or features of", sentence: "The Victorian era was characterized by rapid industrialization and strict social norms.", sentence_trans: "維多利亞時代的特徵是快速的工業化和嚴格的社會規範。", synonyms: ["distinguish", "define"], phrases: ["characterized by"] }] }] },
    { id: "c049", word: "Charitable", ipa: "/ˈtʃær.ə.tə.bəl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "慈善的", def_en: "relating to the assistance of those in need", sentence: "Tax deductions are available for contributions made to registered charitable organizations.", sentence_trans: "捐贈給註冊慈善組織的款項可獲得稅收減免。", synonyms: ["philanthropic", "benevolent"], phrases: ["charitable trust"] }] }] },
    { id: "c050", word: "Check-in", ipa: "/ˈtʃek.ɪn/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "報到；登機手續", def_en: "the act of reporting one's presence", sentence: "Online check-in has streamlined the process for air travelers, reducing wait times at the airport.", sentence_trans: "線上報到簡化了航空旅客的流程，減少了在機場的等待時間。", synonyms: [], phrases: ["check-in counter"] }] }] },
    { id: "c051", word: "Checkout", ipa: "/ˈtʃek.aʊt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "結帳；退房", def_en: "a point at which goods are paid for", sentence: "Automated checkout systems are replacing traditional cashiers in many supermarkets.", sentence_trans: "自動結帳系統正在許多超市取代傳統收銀員。", synonyms: [], phrases: ["checkout counter"] }] }] },
    { id: "c052", word: "Checkup", ipa: "/ˈtʃek.ʌp/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "健康檢查", def_en: "a thorough medical examination", sentence: "An annual medical checkup is crucial for the early detection of potential health issues.", sentence_trans: "年度健康檢查對於早期發現潛在健康問題至關重要。", synonyms: ["examination", "inspection"], phrases: ["routine checkup"] }] }] },
    { id: "c053", word: "Chef", ipa: "/ʃef/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "主廚", def_en: "a professional cook", sentence: "The executive chef oversees all culinary operations within the luxury hotel.", sentence_trans: "行政主廚監督豪華飯店內的所有烹飪運作。", synonyms: ["cook"], phrases: ["master chef"] }] }] },
    { id: "c054", word: "Chemist", ipa: "/ˈkem.ɪst/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "化學家；藥劑師", def_en: "an expert in chemistry", sentence: "The chemist analyzed the soil samples to determine the level of heavy metal contamination.", sentence_trans: "化學家分析土壤樣本以確定重金屬污染的程度。", synonyms: ["scientist", "pharmacist"], phrases: [] }] }] },
    { id: "c055", word: "Chestnut", ipa: "/ˈtʃes.nʌt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "栗子", def_en: "a glossy brown nut", sentence: "The fungal blight devastated the American chestnut population in the early 20th century.", sentence_trans: "真菌枯萎病在20世紀初摧毀了美洲栗樹的數量。", synonyms: [], phrases: [] }] }] },
    { id: "c056", word: "Chili", ipa: "/ˈtʃɪl.i/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "辣椒", def_en: "a small hot-tasting pepper", sentence: "Capsaicin is the chemical compound responsible for the heat in chili peppers.", sentence_trans: "辣椒素是導致辣椒發熱的化學化合物。", synonyms: [], phrases: ["chili powder"] }] }] },
    { id: "c057", word: "Chimpanzee", ipa: "/ˌtʃɪm.pænˈziː/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "黑猩猩", def_en: "a great ape", sentence: "Research on chimpanzees has provided valuable insights into the evolution of human social behavior.", sentence_trans: "對黑猩猩的研究為人類社會行為的演化提供了寶貴的見解。", synonyms: ["chimp"], phrases: [] }] }] },
    { id: "c058", word: "Chirp", ipa: "/tʃɜːp/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "發出啾啾聲", def_en: "make a short, sharp, high-pitched sound", sentence: "The distinct chirp of the crickets signaled the arrival of evening in the countryside.", sentence_trans: "蟋蟀獨特的叫聲標誌著鄉村夜晚的到來。", synonyms: ["tweet", "peep"], phrases: [] }] }] },
    { id: "c059", word: "Choir", ipa: "/kwaɪər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "合唱團", def_en: "an organized group of singers", sentence: "The cathedral choir is renowned for its performance of sacred baroque music.", sentence_trans: "大教堂合唱團以其巴洛克聖樂的表演而聞名。", synonyms: ["chorus", "ensemble"], phrases: [] }] }] },
    { id: "c060", word: "Cholesterol", ipa: "/kəˈles.tər.ɒl/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "膽固醇", def_en: "a fatty substance in the body", sentence: "High levels of LDL cholesterol are a major risk factor for developing cardiovascular disease.", sentence_trans: "高水平的低密度脂蛋白膽固醇是發展心血管疾病的主要危險因素。", synonyms: [], phrases: ["cholesterol level"] }] }] },
    { id: "c061", word: "Chord", ipa: "/kɔːd/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "和弦", def_en: "a group of notes sounded together", sentence: "The song opens with a complex minor chord that sets a melancholic tone for the piece.", sentence_trans: "這首歌以一個複雜的小調和弦開頭，為整首曲子設定了憂鬱的基調。", synonyms: [], phrases: ["strike a chord"] }] }] },
    { id: "c062", word: "Chore", ipa: "/tʃɔːr/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "雜務；家務", def_en: "a routine task", sentence: "Automated appliances have liberated many people from the drudgery of daily household chores.", sentence_trans: "自動化電器已將許多人從繁重的日常家務中解放出來。", synonyms: ["task", "duty"], phrases: ["household chores"] }] }] },
    { id: "c063", word: "Chronic", ipa: "/ˈkrɒn.ɪk/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "慢性的；長期的", def_en: "persisting for a long time", sentence: "Chronic stress can have detrimental effects on the immune system over time.", sentence_trans: "長期壓力會隨著時間的推移對免疫系統產生不利影響。", synonyms: ["persistent", "long-term"], phrases: ["chronic disease"] }] }] },
    { id: "c064", word: "Chubby", ipa: "/ˈtʃʌb.i/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "圓胖的", def_en: "plump and rounded", sentence: "Childhood obesity is distinct from merely being chubby and carries long-term health risks.", sentence_trans: "兒童肥胖不同於僅僅是圓胖，並帶有長期的健康風險。", synonyms: ["plump", "portly"], phrases: [] }] }] },
    { id: "c065", word: "Chunk", ipa: "/tʃʌŋk/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "大塊；部分", def_en: "a thick, solid piece", sentence: "A significant chunk of the national budget is allocated to defense and healthcare.", sentence_trans: "國家預算的一大部分被分配給國防和醫療保健。", synonyms: ["block", "portion"], phrases: ["chunk of text"] }] }] },
    { id: "c066", word: "Cigar", ipa: "/sɪˈɡɑːr/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "雪茄", def_en: "a cylinder of tobacco for smoking", sentence: "The trade embargo historically prohibited the importation of Cuban cigars into the US.", sentence_trans: "貿易禁運歷史上禁止將古巴雪茄進口到美國。", synonyms: [], phrases: [] }] }] },
    { id: "c067", word: "Circuit", ipa: "/ˈsɜː.kɪt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "電路；巡迴", def_en: "a roughly circular line, route, or movement", sentence: "A short circuit in the outdated wiring was identified as the primary cause of the fire.", sentence_trans: "過時線路中的短路被認定為火災的主要原因。", synonyms: ["loop", "track"], phrases: ["integrated circuit"] }] }] },
    { id: "c068", word: "Cite", ipa: "/saɪt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "引用；舉例", def_en: "quote as evidence", sentence: "The author cites numerous peer-reviewed studies to support his argument regarding climate change.", sentence_trans: "作者引用了大量同行評審的研究來支持他關於氣候變遷的論點。", synonyms: ["quote", "mention", "reference"], phrases: ["cite an example"] }] }] },
    { id: "c069", word: "Citizenship", ipa: "/ˈsɪt.ɪ.zən.ʃɪp/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "公民身分", def_en: "the position or status of being a citizen", sentence: "The government has tightened the requirements for granting citizenship to foreign nationals.", sentence_trans: "政府已經收緊了給予外國人公民身分的要求。", synonyms: ["nationality"], phrases: ["dual citizenship"] }] }] },
    { id: "c070", word: "Civic", ipa: "/ˈsɪv.ɪk/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "公民的；城市的", def_en: "relating to a city or town", sentence: "Voting in elections is considered a fundamental civic duty in a democratic society.", sentence_trans: "在民主社會中，選舉投票被視為一項基本的公民義務。", synonyms: ["municipal", "public"], phrases: ["civic pride", "civic duty"] }] }] },
    
    // --- C2: Civilize to Conspiracy ---
    { id: "c071", word: "Civilize", ipa: "/ˈsɪv.əl.aɪz/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "使文明；教化", def_en: "bring to a stage of social development", sentence: "Historically, colonial powers often claimed a mission to civilize indigenous populations as a justification for expansion.", sentence_trans: "歷史上，殖民大國常聲稱有教化原住民的使命，以此作為擴張的正當理由。", synonyms: ["enlighten", "cultivate"], phrases: [] }] }] },
    { id: "c072", word: "Clarity", ipa: "/ˈklær.ə.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "清晰；清楚", def_en: "the quality of being coherent and intelligible", sentence: "The report lacks clarity regarding the implementation timeline of the new safety protocols.", sentence_trans: "該報告關於新安全規程的實施時間表缺乏清晰度。", synonyms: ["lucidity", "clearness"], phrases: ["clarity of thought"] }] }] },
    { id: "c073", word: "Clinical", ipa: "/ˈklɪn.ɪ.kəl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "臨床的；冷靜的", def_en: "relating to the observation and treatment of patients", sentence: "The new drug showed promising results in early clinical trials for treating Alzheimer's disease.", sentence_trans: "這種新藥在治療阿茲海默症的早期臨床試驗中顯示出有希望的結果。", synonyms: ["medical"], phrases: ["clinical trial", "clinical depression"] }] }] },
    { id: "c074", word: "Closure", ipa: "/ˈkləʊ.ʒər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "關閉；終結", def_en: "the act of closing something", sentence: "The victim's family sought closure through the judicial process after years of uncertainty.", sentence_trans: "受害者家屬在多年的不確定後，透過司法程序尋求了結。", synonyms: ["conclusion", "end"], phrases: ["bring closure"] }] }] },
    { id: "c075", word: "Coalition", ipa: "/kəʊ.əˈlɪʃ.ən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "聯盟", def_en: "an alliance for combined action", sentence: "A coalition of environmental groups is lobbying the government for stricter pollution controls.", sentence_trans: "一個環保團體聯盟正在遊說政府實施更嚴格的污染控制。", synonyms: ["alliance", "union"], phrases: ["form a coalition"] }] }] },
    { id: "c076", word: "Cognitive", ipa: "/ˈkɒɡ.nə.tɪv/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "認知的", def_en: "relating to cognition", sentence: "Cognitive decline is a common symptom associated with aging, but mental exercises can delay it.", sentence_trans: "認知衰退是與衰老相關的常見症狀，但心理鍛煉可以延緩它。", synonyms: ["mental", "intellectual"], phrases: ["cognitive skills", "cognitive therapy"] }] }] },
    { id: "c077", word: "Coherent", ipa: "/kəʊˈhɪə.rənt/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "連貫的；有條理的", def_en: "logical and consistent", sentence: "The candidate failed to present a coherent strategy for economic recovery during the debate.", sentence_trans: "候選人在辯論中未能提出連貫的經濟復甦策略。", synonyms: ["logical", "consistent"], phrases: ["coherent argument"] }] }] },
    { id: "c078", word: "Coincidence", ipa: "/kəʊˈɪn.sɪ.dəns/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "巧合", def_en: "a remarkable concurrence of events", sentence: "It was no coincidence that the two market crashes occurred under similar economic conditions.", sentence_trans: "兩次市場崩盤發生在類似的經濟條件下絕非巧合。", synonyms: ["accident", "chance"], phrases: ["by coincidence"] }] }] },
    { id: "c079", word: "Collaboration", ipa: "/kəˌlæb.əˈreɪ.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "合作", def_en: "the action of working with someone to produce something", sentence: "The scientific breakthrough was the result of international collaboration between universities.", sentence_trans: "這一科學突破是大學之間國際合作的結果。", synonyms: ["cooperation", "partnership"], phrases: ["in collaboration with"] }] }] },
    { id: "c080", word: "Collective", ipa: "/kəˈlek.tɪv/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "集體的", def_en: "done by people acting as a group", sentence: "We bear a collective responsibility to protect the environment for future generations.", sentence_trans: "我們對保護環境以造福後代負有集體責任。", synonyms: ["joint", "shared"], phrases: ["collective bargaining"] }] }] },
    { id: "c081", word: "Collision", ipa: "/kəˈlɪʒ.ən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "碰撞；衝突", def_en: "an instance of one moving object striking another", sentence: "The collision of tectonic plates is the primary cause of earthquakes in this region.", sentence_trans: "板塊的碰撞是該地區地震的主要原因。", synonyms: ["crash", "impact"], phrases: ["head-on collision"] }] }] },
    { 
        id: "c082", word: "Combat", ipa: "/ˈkɒm.bæt/", priority: 10, 
        meanings: [
            { pos: "v.", items: [{ def_zh: "打擊；戰鬥", def_en: "take action to reduce or destroy", sentence: "The government must invest more resources to combat poverty and inequality effectively.", sentence_trans: "政府必須投入更多資源來有效打擊貧困和不平等。", synonyms: ["fight", "tackle"], phrases: ["combat crime"] }] },
            { pos: "n.", items: [{ def_zh: "戰鬥", def_en: "fighting between armed forces", sentence: "The soldiers were trained for close-quarters combat in urban environments.", sentence_trans: "士兵們接受了在城市環境中進行近距離戰鬥的訓練。", synonyms: ["battle", "conflict"], phrases: ["hand-to-hand combat"] }] }
        ] 
    },
    { id: "c083", word: "Commence", ipa: "/kəˈmens/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "開始", def_en: "begin", sentence: "The construction project is scheduled to commence in the next fiscal quarter.", sentence_trans: "建設項目定於下個財政季度開始。", synonyms: ["begin", "start"], phrases: ["commence proceedings"] }] }] },
    { id: "c084", word: "Commission", ipa: "/kəˈmɪʃ.ən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "委員會；佣金", def_en: "a group of people entrusted with authority", sentence: "An independent commission was established to investigate the allegations of corruption.", sentence_trans: "成立了一個獨立委員會來調查腐敗指控。", synonyms: ["committee", "board"], phrases: ["royal commission"] }] }] },
    { id: "c085", word: "Commitment", ipa: "/kəˈmɪt.mənt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "承諾；投入", def_en: "the state of being dedicated to a cause", sentence: "The company reaffirmed its commitment to achieving carbon neutrality by 2030.", sentence_trans: "公司重申了其在2030年實現碳中和的承諾。", synonyms: ["dedication", "pledge"], phrases: ["make a commitment"] }] }] },
    { id: "c086", word: "Commodity", ipa: "/kəˈmɒd.ə.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "商品", def_en: "a raw material that can be bought and sold", sentence: "Clean water is becoming a scarce commodity in many arid regions due to climate change.", sentence_trans: "由於氣候變遷，在許多乾旱地區，潔淨水正成為一種稀缺商品。", synonyms: ["product", "goods"], phrases: ["commodity market"] }] }] },
    { id: "c087", word: "Compatible", ipa: "/kəmˈpæt.ə.bəl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "相容的", def_en: "able to exist or occur together without conflict", sentence: "Rapid economic growth is not always compatible with environmental preservation.", sentence_trans: "快速的經濟增長並不總是與環境保護相容。", synonyms: ["consistent", "harmonious"], phrases: ["compatible with"] }] }] },
    { id: "c088", word: "Compel", ipa: "/kəmˈpel/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "強迫", def_en: "force or oblige", sentence: "The overwhelming evidence compelled the jury to reach a guilty verdict.", sentence_trans: "壓倒性的證據迫使陪審團做出有罪判決。", synonyms: ["force", "coerce"], phrases: ["feel compelled"] }] }] },
    { id: "c089", word: "Compensate", ipa: "/ˈkɒm.pən.seɪt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "補償", def_en: "give something in recognition of loss", sentence: "Workers should be adequately compensated for the risks associated with hazardous working conditions.", sentence_trans: "工人應因危險工作條件相關的風險獲得適當補償。", synonyms: ["reimburse", "repay"], phrases: ["compensate for"] }] }] },
    { id: "c090", word: "Competence", ipa: "/ˈkɒm.pɪ.təns/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "能力；勝任", def_en: "the ability to do something successfully", sentence: "The assessment is designed to evaluate the students' linguistic competence in a foreign language.", sentence_trans: "該評估旨在評估學生的外語語言能力。", synonyms: ["capability", "proficiency"], phrases: ["professional competence"] }] }] },
    { id: "c091", word: "Compile", ipa: "/kəmˈpaɪl/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "編製；匯編", def_en: "produce by assembling information", sentence: "Researchers are compiling a comprehensive database of genetic mutations.", sentence_trans: "研究人員正在編製一個全面的基因突變資料庫。", synonyms: ["assemble", "gather"], phrases: ["compile data"] }] }] },
    { 
        id: "c092", word: "Complement", ipa: "/ˈkɒm.plɪ.ment/", priority: 10, 
        meanings: [
            { pos: "v.", items: [{ def_zh: "補充；相配", def_en: "add to in a way that enhances", sentence: "Theoretical knowledge should complement practical experience in professional training.", sentence_trans: "在專業培訓中，理論知識應與實踐經驗相輔相成。", synonyms: ["enhance", "complete"], phrases: [] }] },
            { pos: "n.", items: [{ def_zh: "補充物", def_en: "a thing that completes or brings to perfection", sentence: "A fine wine is the perfect complement to a gourmet meal.", sentence_trans: "美酒是美食的完美補充。", synonyms: ["addition"], phrases: [] }] }
        ] 
    },
    { id: "c093", word: "Complexity", ipa: "/kəmˈplek.sə.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "複雜性", def_en: "the state of being complicated", sentence: "The complexity of the human brain's neural network is not yet fully understood.", sentence_trans: "人腦神經網絡的複雜性尚未被完全理解。", synonyms: ["intricacy"], phrases: [] }] }] },
    { id: "c094", word: "Compliance", ipa: "/kəmˈplaɪ.əns/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "遵守；合規", def_en: "the action of complying with a command", sentence: "Strict compliance with safety regulations is mandatory in the construction industry.", sentence_trans: "在建築業中，嚴格遵守安全法規是強制的。", synonyms: ["obedience", "conformity"], phrases: ["in compliance with"] }] }] },
    { id: "c095", word: "Component", ipa: "/kəmˈpəʊ.nənt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "成分；組件", def_en: "a part or element of a larger whole", sentence: "Trust is a vital component of any successful international relationship.", sentence_trans: "信任是任何成功國際關係的重要組成部分。", synonyms: ["element", "constituent"], phrases: ["key component"] }] }] },
    { id: "c096", word: "Comprehend", ipa: "/ˌkɒm.prɪˈhend/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "理解", def_en: "grasp mentally; understand", sentence: "It is difficult to comprehend the sheer scale of the universe without visual aids.", sentence_trans: "沒有視覺輔助，很難理解宇宙的巨大規模。", synonyms: ["understand", "grasp"], phrases: [] }] }] },
    { id: "c097", word: "Comprehensive", ipa: "/ˌkɒm.prɪˈhen.sɪv/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "全面的", def_en: "including all or nearly all elements", sentence: "The government conducted a comprehensive review of the education system to identify areas for reform.", sentence_trans: "政府對教育體系進行了全面審查，以確定需要改革的領域。", synonyms: ["complete", "thorough"], phrases: ["comprehensive study"] }] }] },
    { id: "c098", word: "Comprise", ipa: "/kəmˈpraɪz/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "包含；由...組成", def_en: "consist of", sentence: "The committee comprises representatives from various industrial sectors.", sentence_trans: "該委員會由來自各個工業部門的代表組成。", synonyms: ["consist of", "include"], phrases: [] }] }] },
    { 
        id: "c099", word: "Compromise", ipa: "/ˈkɒm.prə.maɪz/", priority: 10, 
        meanings: [
            { pos: "n.", items: [{ def_zh: "妥協", def_en: "an agreement reached by making concessions", sentence: "Reaching a compromise is essential in diplomatic negotiations to avoid conflict.", sentence_trans: "在外交談判中達成妥協對於避免衝突至關重要。", synonyms: ["settlement"], phrases: ["reach a compromise"] }] },
            { pos: "v.", items: [{ def_zh: "危害；妥協", def_en: "endanger; settle by concession", sentence: "We should not compromise safety standards for the sake of profit.", sentence_trans: "我們不應為了利潤而危害安全標準。", synonyms: ["risk", "undermine"], phrases: ["compromise safety"] }] }
        ] 
    },
    { id: "c100", word: "Compulsory", ipa: "/kəmˈpʌl.sər.i/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "強制的", def_en: "required by law or a rule", sentence: "English is a compulsory subject in most secondary schools across the country.", sentence_trans: "在全國大多數中學，英語是必修科目。", synonyms: ["mandatory", "obligatory"], phrases: ["compulsory education"] }] }] },
    { id: "c101", word: "Conceal", ipa: "/kənˈsiːl/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "隱藏", def_en: "keep from sight; hide", sentence: "He tried to conceal his true feelings behind a mask of indifference.", sentence_trans: "他試圖用冷漠的面具來掩飾他的真實感受。", synonyms: ["hide", "mask"], phrases: ["conceal the truth"] }] }] },
    { id: "c102", word: "Concede", ipa: "/kənˈsiːd/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "承認；讓步", def_en: "admit that something is true", sentence: "The government conceded that the economic policy had failed to meet its targets.", sentence_trans: "政府承認該經濟政策未能達到目標。", synonyms: ["admit", "acknowledge"], phrases: ["concede defeat"] }] }] },
    { id: "c103", word: "Conceive", ipa: "/kənˈsiːv/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "構想", def_en: "form or devise in the mind", sentence: "It is hard to conceive of a modern society functioning without the internet.", sentence_trans: "很難想像一個現代社會在沒有網際網路的情況下運作。", synonyms: ["imagine", "envision"], phrases: [] }] }] },
    { id: "c104", word: "Concise", ipa: "/kənˈsaɪs/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "簡潔的", def_en: "giving a lot of information clearly and briefly", sentence: "Please provide a concise summary of the report's main findings.", sentence_trans: "請提供報告主要發現的簡潔摘要。", synonyms: ["succinct", "brief"], phrases: ["clear and concise"] }] }] },
    { id: "c105", word: "Condemn", ipa: "/kənˈdem/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "譴責", def_en: "express complete disapproval of", sentence: "The international community united to condemn the act of terrorism.", sentence_trans: "國際社會團結一致譴責恐怖主義行為。", synonyms: ["denounce", "censure"], phrases: [] }] }] },
    { 
        id: "c106", word: "Conduct", ipa: "/ˈkɒn.dʌkt/", priority: 10, 
        meanings: [
            { pos: "n.", items: [{ def_zh: "行為", def_en: "manner of behaving", sentence: "The company has a strict code of conduct that all employees must follow.", sentence_trans: "公司有嚴格的行為準則，所有員工都必須遵守。", synonyms: ["behavior"], phrases: ["code of conduct"] }] },
            { pos: "v.", items: [{ def_zh: "實施；指揮", def_en: "organize and carry out", sentence: "The university conducts extensive research on renewable energy sources.", sentence_trans: "該大學對可再生能源進行廣泛的研究。", synonyms: ["perform", "manage"], phrases: ["conduct research"] }] }
        ] 
    },
    { id: "c107", word: "Confidential", ipa: "/ˌkɒn.fɪˈden.ʃəl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "機密的", def_en: "intended to be kept secret", sentence: "Medical records are strictly confidential and cannot be released without patient consent.", sentence_trans: "醫療記錄是嚴格保密的，未經患者同意不得發布。", synonyms: ["secret", "private"], phrases: ["confidential information"] }] }] },
    { id: "c108", word: "Confine", ipa: "/kənˈfaɪn/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "限制", def_en: "keep within limits", sentence: "Please confine your discussion to the agenda items listed below.", sentence_trans: "請將您的討論限制在下列議程項目上。", synonyms: ["restrict", "limit"], phrases: ["confine to"] }] }] },
    { id: "c109", word: "Conform", ipa: "/kənˈfɔːm/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "遵守；符合", def_en: "comply with rules", sentence: "All imported goods must conform to the country's safety standards.", sentence_trans: "所有進口商品必須符合該國的安全標準。", synonyms: ["comply", "adhere"], phrases: ["conform to"] }] }] },
    { id: "c110", word: "Confront", ipa: "/kənˈfrʌnt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "面對；對抗", def_en: "meet face to face with hostile intent", sentence: "We must confront the reality of the economic crisis and take immediate action.", sentence_trans: "我們必須面對經濟危機的現實並立即採取行動。", synonyms: ["face", "challenge"], phrases: ["confront a problem"] }] }] },
    { id: "c111", word: "Consensus", ipa: "/kənˈsen.səs/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "共識", def_en: "general agreement", sentence: "There is a growing scientific consensus on the causes of climate change.", sentence_trans: "關於氣候變遷的原因，科學共識正日益增長。", synonyms: ["agreement", "accord"], phrases: ["reach a consensus"] }] }] },
    { 
        id: "c112", word: "Consent", ipa: "/kənˈsent/", priority: 10, 
        meanings: [
            { pos: "n.", items: [{ def_zh: "同意", def_en: "permission", sentence: "Informed consent is required before any medical procedure can be performed.", sentence_trans: "在進行任何醫療程序之前，必須獲得知情同意。", synonyms: ["agreement", "permission"], phrases: ["mutual consent"] }] },
            { pos: "v.", items: [{ def_zh: "同意", def_en: "agree to do something", sentence: "The patient consented to the experimental treatment after understanding the risks.", sentence_trans: "病人在了解風險後同意接受實驗性治療。", synonyms: ["agree", "assent"], phrases: [] }] }
        ] 
    },
    { id: "c113", word: "Conservation", ipa: "/ˌkɒn.səˈveɪ.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "保育", def_en: "preservation", sentence: "Wildlife conservation is critical for maintaining global biodiversity.", sentence_trans: "野生動物保育對於維持全球生物多樣性至關重要。", synonyms: ["preservation", "protection"], phrases: ["environmental conservation"] }] }] },
    { id: "c114", word: "Conserve", ipa: "/kənˈsɜːv/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "節約；保護", def_en: "protect from harm or overuse", sentence: "Efforts to conserve energy are encouraged to reduce environmental impact.", sentence_trans: "鼓勵節約能源的努力以減少環境影響。", synonyms: ["save", "preserve"], phrases: ["conserve resources"] }] }] },
    { id: "c115", word: "Considerate", ipa: "/kənˈsɪd.ər.ət/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "體貼的", def_en: "careful not to inconvenience others", sentence: "It is considerate to lower your voice when studying in the library.", sentence_trans: "在圖書館學習時降低聲音是體貼的表現。", synonyms: ["thoughtful", "kind"], phrases: [] }] }] },
    { id: "c116", word: "Conspiracy", ipa: "/kənˈspɪr.ə.si/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "陰謀", def_en: "a secret plan to do something unlawful", sentence: "He was arrested for involvement in a conspiracy to commit financial fraud.", sentence_trans: "他因涉嫌金融欺詐陰謀而被捕。", synonyms: ["plot", "scheme"], phrases: ["conspiracy theory"] }] }] },
    // --- C3: Constant to Cynical (Updated with High Quality Sentences) ---
    { 
        id: "c176", word: "Constant", ipa: "/ˈkɒn.stənt/", priority: 10, 
        meanings: [
            { pos: "adj.", items: [{ def_zh: "持續的；恆定的", def_en: "occurring continuously over a period of time", sentence: "The patient requires constant monitoring to ensure his condition remains stable.", sentence_trans: "病人需要持續監控以確保病情穩定。", synonyms: ["continuous", "persistent"], phrases: ["constant reminder"] }] },
            { pos: "n.", items: [{ def_zh: "常數", def_en: "a quantity that does not change", sentence: "In this equation, 'c' represents a constant value.", sentence_trans: "在這個方程式中，'c' 代表一個常數值。", synonyms: [], phrases: [] }] }
        ] 
    },
    { id: "c177", word: "Constitutional", ipa: "/ˌkɒn.stɪˈtjuː.ʃən.əl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "憲法的；符合憲法的", def_en: "relating to an established set of principles governing a state", sentence: "The supreme court ruled that the new surveillance law was a violation of constitutional rights.", sentence_trans: "最高法院裁定新的監視法違反了憲法權利。", synonyms: ["legal", "statutory"], phrases: ["constitutional reform"] }] }] },
    { id: "c178", word: "Constraint", ipa: "/kənˈstreɪnt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "限制；約束", def_en: "a limitation or restriction", sentence: "Financial constraints have forced the department to reduce its research budget.", sentence_trans: "財務限制迫使該部門削減研究預算。", synonyms: ["restriction", "limitation"], phrases: ["budget constraints"] }] }] },
    { id: "c179", word: "Consultation", ipa: "/ˌkɒn.sʌlˈteɪ.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "諮詢；商議", def_en: "the action or process of formally consulting or discussing", sentence: "The government announced a public consultation period regarding the proposed urban development.", sentence_trans: "政府宣布了關於擬議城市發展的公眾諮詢期。", synonyms: ["discussion", "deliberation"], phrases: ["public consultation"] }] }] },
    { id: "c180", word: "Consumption", ipa: "/kənˈsʌmp.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "消耗；消費", def_en: "the using up of a resource", sentence: "The rapid consumption of fossil fuels contributes significantly to global greenhouse gas emissions.", sentence_trans: "化石燃料的快速消耗對全球溫室氣體排放有顯著影響。", synonyms: ["usage", "expenditure"], phrases: ["energy consumption"] }] }] },
    { id: "c181", word: "Contagious", ipa: "/kənˈteɪ.dʒəs/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "接觸傳染的；有感染力的", def_en: "spread from one person or organism to another by direct or indirect contact", sentence: "Since the virus is highly contagious, strict quarantine measures were implemented.", sentence_trans: "由於該病毒具有高度傳染性，因此實施了嚴格的隔離措施。", synonyms: ["infectious", "transmittable"], phrases: ["highly contagious"] }] }] },
    { id: "c182", word: "Contaminate", ipa: "/kənˈtæm.ɪ.neɪt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "污染；弄髒", def_en: "make (something) impure by exposure to or addition of a poisonous or polluting substance", sentence: "Industrial waste was found to contaminate the local water supply, posing a health risk.", sentence_trans: "發現工業廢物污染了當地的供水系統，構成了健康風險。", synonyms: ["pollute", "taint"], phrases: ["contaminated soil"] }] }] },
    { id: "c183", word: "Contemplate", ipa: "/ˈkɒn.təm.pleɪt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "沉思；凝視", def_en: "look thoughtfully for a long time at; think about", sentence: "Before making a final decision, he needed time to contemplate the consequences of his actions.", sentence_trans: "在做出最終決定之前，他需要時間沉思自己行為的後果。", synonyms: ["ponder", "consider"], phrases: ["contemplate the future"] }] }] },
    { id: "c184", word: "Contemporary", ipa: "/kənˈtem.pər.ər.i/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "當代的；同時代的", def_en: "living or occurring at the same time; belonging to or occurring in the present", sentence: "Contemporary architecture often prioritizes sustainability and energy efficiency.", sentence_trans: "當代建築通常優先考慮永續性和能源效率。", synonyms: ["modern", "current"], phrases: ["contemporary art"] }] }] },
    { id: "c185", word: "Contempt", ipa: "/kənˈtempt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "輕視；蔑視", def_en: "the feeling that a person or a thing is beneath consideration", sentence: "He showed utter contempt for the court's authority by refusing to testify.", sentence_trans: "他拒絕作證，表現出對法庭權威的徹底蔑視。", synonyms: ["scorn", "disdain"], phrases: ["hold in contempt"] }] }] },
    { id: "c186", word: "Contend", ipa: "/kənˈtend/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "聲稱；競爭", def_en: "assert something as a position in an argument", sentence: "Critics contend that the education system fails to prepare students for the modern workforce.", sentence_trans: "批評者聲稱，教育體系未能讓學生為現代勞動力市場做好準備。", synonyms: ["assert", "maintain"], phrases: ["contend with"] }] }] },
    { id: "c187", word: "Contention", ipa: "/kənˈten.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "爭論；論點", def_en: "heated disagreement", sentence: "The proposed budget cuts remain a major point of contention between the two parties.", sentence_trans: "擬議的預算削減仍然是兩黨之間爭論的主要焦點。", synonyms: ["dispute", "argument"], phrases: ["bone of contention"] }] }] },
    { id: "c188", word: "Contestant", ipa: "/kənˈtes.tənt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "參賽者", def_en: "a person who takes part in a contest", sentence: "Each contestant was given five minutes to present their business idea to the judges.", sentence_trans: "每位參賽者有五分鐘時間向評委展示他們的商業構想。", synonyms: ["competitor", "participant"], phrases: [] }] }] },
    { id: "c189", word: "Continental", ipa: "/ˌkɒn.tɪˈnen.təl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "大陸的", def_en: "forming or belonging to a continent", sentence: "The continental shelf is rich in natural resources like oil and gas.", sentence_trans: "大陸棚富含石油和天然氣等自然資源。", synonyms: [], phrases: ["continental climate"] }] }] },
    { id: "c190", word: "Continuity", ipa: "/ˌkɒn.tɪˈnjuː.ə.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "連續性", def_en: "the unbroken and consistent existence or operation of something", sentence: "We need to ensure business continuity in the event of a natural disaster.", sentence_trans: "我們需要確保在發生自然災害時業務的連續性。", synonyms: ["consistency", "stability"], phrases: [] }] }] },
    { id: "c191", word: "Contractor", ipa: "/kənˈtræk.tər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "承包商", def_en: "a person or company that undertakes a contract", sentence: "The government hired a private contractor to build the new highway.", sentence_trans: "政府僱用了一家私人承包商來建造新高速公路。", synonyms: [], phrases: ["general contractor"] }] }] },
    { id: "c192", word: "Contradict", ipa: "/ˌkɒn.trəˈdɪkt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "反駁；與...矛盾", def_en: "deny the truth of (a statement) by asserting the opposite", sentence: "The witness's statement appeared to contradict the forensic evidence found at the scene.", sentence_trans: "證人的陳述似乎與現場發現的法醫證據相矛盾。", synonyms: ["deny", "refute"], phrases: ["contradict oneself"] }] }] },
    { id: "c193", word: "Contradiction", ipa: "/ˌkɒn.trəˈdɪk.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "矛盾", def_en: "a combination of statements, ideas, or features of a situation that are opposed to one another", sentence: "There is a fundamental contradiction between wanting lower taxes and demanding better public services.", sentence_trans: "想要減稅和要求更好的公共服務之間存在根本的矛盾。", synonyms: ["inconsistency", "paradox"], phrases: ["in contradiction to"] }] }] },
    { id: "c194", word: "Controversial", ipa: "/ˌkɒn.trəˈvɜː.ʃəl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "有爭議的", def_en: "giving rise or likely to give rise to public disagreement", sentence: "The decision to build a nuclear power plant in the area was highly controversial.", sentence_trans: "在該地區建造核電站的決定極具爭議。", synonyms: ["contentious", "disputed"], phrases: ["controversial issue"] }] }] },
    { id: "c195", word: "Controversy", ipa: "/ˈkɒn.trə.vɜː.si/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "爭議；爭論", def_en: "disagreement, typically when prolonged, public, and heated", sentence: "The new healthcare policy has sparked widespread controversy among medical professionals.", sentence_trans: "新的醫療保健政策在醫療專業人員中引發了廣泛爭議。", synonyms: ["dispute", "debate"], phrases: ["cause controversy"] }] }] },
    { id: "c196", word: "Convene", ipa: "/kənˈviːn/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "召集；集合", def_en: "come or bring together for a meeting or activity", sentence: "The United Nations Security Council will convene an emergency meeting tomorrow.", sentence_trans: "聯合國安理會將於明天召開緊急會議。", synonyms: ["assemble", "gather"], phrases: ["convene a meeting"] }] }] },
    { id: "c197", word: "Conversion", ipa: "/kənˈvɜː.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "轉換；轉變", def_en: "the process of changing or causing something to change from one form to another", sentence: "The conversion of the old factory into luxury apartments took two years.", sentence_trans: "將舊工廠改建為豪華公寓花了兩年時間。", synonyms: ["transformation", "change"], phrases: ["currency conversion"] }] }] },
    { 
        id: "c198", word: "Convert", ipa: "/kənˈvɜːt/", priority: 10, 
        meanings: [
            { pos: "v.", items: [{ def_zh: "轉變；改變信仰", def_en: "cause to change in form, character, or function", sentence: "Solar panels are designed to convert sunlight directly into electricity.", sentence_trans: "太陽能電池板設計用於將陽光直接轉化為電能。", synonyms: ["transform", "alter"], phrases: ["convert into"] }] },
            { pos: "n.", items: [{ def_zh: "改變信仰者", def_en: "a person who has been persuaded to change their religious faith", sentence: "He is a recent convert to Buddhism.", sentence_trans: "他是最近皈依佛教的信徒。", synonyms: [], phrases: [] }] }
        ] 
    },
    { 
        id: "c199", word: "Convict", ipa: "/kənˈvɪkt/", priority: 10, 
        meanings: [
            { pos: "v.", items: [{ def_zh: "定罪", def_en: "declare (someone) to be guilty of a criminal offense", sentence: "He was convicted of fraud based on the evidence presented.", sentence_trans: "根據提出的證據，他被判欺詐罪。", synonyms: ["condemn"], phrases: [] }] },
            { pos: "n.", items: [{ def_zh: "囚犯", def_en: "a person found guilty of a criminal offense", sentence: "The prison provides rehabilitation programs for convicts.", sentence_trans: "監獄為囚犯提供康復計畫。", synonyms: ["prisoner", "inmate"], phrases: [] }] }
        ] 
    },
    { id: "c200", word: "Conviction", ipa: "/kənˈvɪk.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "定罪；堅定的信念", def_en: "a formal declaration that someone is guilty; a firmly held belief", sentence: "Despite the lack of physical evidence, he held a strong conviction that the theory was correct.", sentence_trans: "儘管缺乏物證，他仍堅信該理論是正確的。", synonyms: ["belief", "opinion"], phrases: ["firm conviction"] }] }] },
    { 
        id: "c201", word: "Coordinate", ipa: "/kəʊˈɔː.dɪ.neɪt/", priority: 10, 
        meanings: [
            { pos: "v.", items: [{ def_zh: "協調；配合", def_en: "bring the different elements of (a complex activity) into a relationship that will ensure efficiency", sentence: "International aid agencies must coordinate their efforts to ensure relief reaches those in need.", sentence_trans: "國際援助機構必須協調其努力，以確保救濟物資送達有需要的人手中。", synonyms: ["organize", "harmonize"], phrases: ["coordinate efforts"] }] },
            { pos: "n.", items: [{ def_zh: "座標", def_en: "each of a group of numbers used to indicate the position of a point", sentence: "The GPS coordinates indicated that we were off course.", sentence_trans: "GPS座標顯示我們偏離了航線。", synonyms: [], phrases: [] }] }
        ] 
    },
    { id: "c202", word: "Copyright", ipa: "/ˈkɒp.i.raɪt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "版權", def_en: "the exclusive legal right to print, publish, etc.", sentence: "Copyright laws protect intellectual property from unauthorized distribution.", sentence_trans: "版權法保護智慧財產權免受未經授權的散佈。", synonyms: [], phrases: ["copyright infringement"] }] }] },
    { id: "c203", word: "Coral", ipa: "/ˈkɒr.əl/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "珊瑚", def_en: "a hard stony substance secreted by certain marine coelenterates", sentence: "Rising ocean temperatures are causing widespread bleaching of coral reefs.", sentence_trans: "海水溫度上升正導致珊瑚礁廣泛白化。", synonyms: [], phrases: ["coral reef"] }] }] },
    { id: "c204", word: "Core", ipa: "/kɔːr/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "核心", def_en: "the part of something that is central to its existence or character", sentence: "Sustainability is at the core of the company's business philosophy.", sentence_trans: "永續性是該公司經營理念的核心。", synonyms: ["center", "nucleus"], phrases: ["core values"] }] }] },
    { id: "c205", word: "Corporate", ipa: "/ˈkɔː.pər.ət/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "公司的；企業的", def_en: "relating to a corporation", sentence: "Corporate social responsibility is now a key component of brand strategy.", sentence_trans: "企業社會責任現在是品牌策略的關鍵組成部分。", synonyms: ["business", "commercial"], phrases: ["corporate culture"] }] }] },
    { id: "c206", word: "Corporation", ipa: "/ˌkɔː.pərˈeɪ.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "公司", def_en: "a large company or group of companies", sentence: "Multinational corporations play a significant role in the global economy.", sentence_trans: "跨國公司在全球經濟中扮演重要角色。", synonyms: ["company", "firm"], phrases: [] }] }] },
    { id: "c207", word: "Corpse", ipa: "/kɔːps/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "屍體", def_en: "a dead body", sentence: "Forensic scientists examined the corpse to determine the cause of death.", sentence_trans: "法醫檢查屍體以確定死因。", synonyms: ["body", "remains"], phrases: [] }] }] },
    { id: "c208", word: "Correlation", ipa: "/ˌkɒr.əˈleɪ.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "相關性；關聯", def_en: "a mutual relationship or connection", sentence: "Studies have consistently shown a positive correlation between education levels and income.", sentence_trans: "研究一致顯示教育水平與收入之間存在正相關。", synonyms: ["connection", "association"], phrases: ["direct correlation"] }] }] },
    { id: "c209", word: "Correspondence", ipa: "/ˌkɒr.ɪˈspɒn.dəns/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "通信；信件；一致", def_en: "communication by exchanging letters; a close similarity", sentence: "There is little correspondence between the ideal world described in the book and reality.", sentence_trans: "書中描述的理想世界與現實之間幾乎沒有一致性。", synonyms: ["communication", "agreement"], phrases: ["in correspondence with"] }] }] },
    { id: "c210", word: "Correspondent", ipa: "/ˌkɒr.ɪˈspɒn.dənt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "特派員；通訊記者", def_en: "a person who writes letters to a person or a newspaper", sentence: "She works as a foreign correspondent in the Middle East for a major news network.", sentence_trans: "她在一家主要新聞網擔任中東地區的外國特派員。", synonyms: ["reporter", "journalist"], phrases: [] }] }] },
    { id: "c211", word: "Corridor", ipa: "/ˈkɒr.ɪ.dɔːr/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "走廊", def_en: "a long passage in a building", sentence: "The long corridor was lined with portraits of former presidents.", sentence_trans: "長長的走廊兩旁掛滿了前總統的肖像。", synonyms: ["hallway", "passage"], phrases: [] }] }] },
    { id: "c212", word: "Corrupt", ipa: "/kəˈrʌpt/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "腐敗的", def_en: "having or showing a willingness to act dishonestly", sentence: "The investigation exposed a corrupt network of officials accepting bribes.", sentence_trans: "調查揭露了一個收受賄賂的腐敗官員網絡。", synonyms: ["dishonest", "unethical"], phrases: ["corrupt practices"] }] }] },
    { id: "c213", word: "Corruption", ipa: "/kəˈrʌp.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "腐敗；貪污", def_en: "dishonest or fraudulent conduct", sentence: "Political corruption is a major obstacle to economic development in many developing countries.", sentence_trans: "政治腐敗是許多發展中國家經濟發展的主要障礙。", synonyms: ["dishonesty", "graft"], phrases: ["fight corruption"] }] }] },
    { id: "c214", word: "Cosmetic", ipa: "/kɒzˈmet.ɪk/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "化妝的；表面的", def_en: "involving treatment intended to restore or improve a person's appearance", sentence: "The changes to the user interface were purely cosmetic and did not improve functionality.", sentence_trans: "使用者介面的更改純粹是表面的，並沒有改善功能。", synonyms: ["superficial"], phrases: ["cosmetic surgery"] }] }] },
    { id: "c215", word: "Cosmetics", ipa: "/kɒzˈmet.ɪks/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "化妝品", def_en: "products applied to the body to improve its appearance", sentence: "The cosmetics industry is highly competitive and driven by brand loyalty.", sentence_trans: "化妝品產業競爭激烈，並受品牌忠誠度驅動。", synonyms: ["makeup"], phrases: [] }] }] },
    { 
        id: "c216", word: "Counsel", ipa: "/ˈkaʊn.səl/", priority: 10, 
        meanings: [
            { pos: "n.", items: [{ def_zh: "建議；法律顧問", def_en: "advice, especially that given formally", sentence: "He sought the counsel of a financial expert before making the investment.", sentence_trans: "他在進行投資前尋求了財務專家的建議。", synonyms: ["advice", "guidance"], phrases: ["legal counsel"] }] },
            { pos: "v.", items: [{ def_zh: "建議；勸告", def_en: "give advice to (someone)", sentence: "The doctor counseled him to change his diet.", sentence_trans: "醫生建議他改變飲食習慣。", synonyms: ["advise"], phrases: [] }] }
        ] 
    },
    { id: "c217", word: "Counselor", ipa: "/ˈkaʊn.səl.ər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "顧問；輔導員", def_en: "a person trained to give guidance", sentence: "The school counselor provides support to students dealing with personal issues.", sentence_trans: "學校輔導員為處理個人問題的學生提供支持。", synonyms: ["advisor", "therapist"], phrases: ["guidance counselor"] }] }] },
    { id: "c218", word: "Counterclockwise", ipa: "/ˌkaʊn.təˈklɒk.waɪz/", priority: 10, meanings: [{ pos: "adv.", items: [{ def_zh: "逆時針地", def_en: "in the opposite direction to the way in which the hands of a clock move", sentence: "To loosen the screw, turn it counterclockwise.", sentence_trans: "要鬆開螺絲，請逆時針轉動它。", synonyms: ["anticlockwise"], phrases: [] }] }] },
    { id: "c219", word: "Counterpart", ipa: "/ˈkaʊn.tə.pɑːt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "對應的人或物", def_en: "a person or thing holding a position corresponding to that of another person or thing in another place", sentence: "The foreign minister met with his counterpart from France to discuss the treaty.", sentence_trans: "外交部長會見了法國外交部長討論該條約。", synonyms: ["equivalent", "peer"], phrases: [] }] }] },
    { id: "c220", word: "Coupon", ipa: "/ˈkuː.pɒn/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "優惠券", def_en: "a voucher entitling the holder to a discount", sentence: "Consumers are increasingly using digital coupons for online shopping.", sentence_trans: "消費者越來越多地使用數位優惠券進行網上購物。", synonyms: ["voucher"], phrases: ["discount coupon"] }] }] },
    { id: "c221", word: "Courteous", ipa: "/ˈkɜː.ti.əs/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "有禮貌的", def_en: "polite, respectful, or considerate in manner", sentence: "The staff were trained to be courteous and professional at all times.", sentence_trans: "員工受訓要隨時保持禮貌和專業。", synonyms: ["polite", "respectful"], phrases: [] }] }] },
    { id: "c222", word: "Courtyard", ipa: "/ˈkɔːt.jɑːd/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "庭院", def_en: "an unroofed area enclosed by walls", sentence: "The apartment complex features a central courtyard with a fountain.", sentence_trans: "該公寓大樓設有一個帶噴泉的中央庭院。", synonyms: ["patio"], phrases: [] }] }] },
    { id: "c223", word: "Coverage", ipa: "/ˈkʌv.ər.ɪdʒ/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "報導；覆蓋範圍", def_en: "the treatment of an issue by the media", sentence: "The election received extensive media coverage across all major networks.", sentence_trans: "這次選舉在所有主要電視網上都獲得了廣泛的媒體報導。", synonyms: ["reporting"], phrases: ["media coverage"] }] }] },
    { id: "c224", word: "Covet", ipa: "/ˈkʌv.ɪt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "覬覦；貪求", def_en: "yearn to possess or have (something)", sentence: "The award is highly coveted by actors in the film industry.", sentence_trans: "該獎項是電影界演員夢寐以求的。", synonyms: ["desire", "crave"], phrases: [] }] }] },
    { id: "c225", word: "Cowardice", ipa: "/ˈkaʊ.ə.dɪs/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "懦弱", def_en: "lack of bravery", sentence: "The soldier was accused of cowardice for abandoning his post.", sentence_trans: "該士兵因棄崗被指控懦弱。", synonyms: ["fearfulness"], phrases: [] }] }] },
    { id: "c226", word: "Cowardly", ipa: "/ˈkaʊ.əd.li/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "懦弱的", def_en: "lacking courage", sentence: "The attack on unarmed civilians was condemned as a cowardly act.", sentence_trans: "對手無寸鐵平民的攻擊被譴責為懦弱的行為。", synonyms: ["timid"], phrases: [] }] }] },
    { id: "c227", word: "Cozy", ipa: "/ˈkəʊ.zi/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "舒適的", def_en: "giving a feeling of comfort, warmth, and relaxation", sentence: "The small cafe offered a cozy atmosphere for reading and relaxing.", sentence_trans: "這家小咖啡館為閱讀和放鬆提供了舒適的氛圍。", synonyms: ["snug", "comfortable"], phrases: [] }] }] },
    { id: "c228", word: "Crackdown", ipa: "/ˈkræk.daʊn/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "鎮壓；嚴厲打擊", def_en: "severe measures to restrict undesirable behavior", sentence: "The government launched a crackdown on illegal gambling operations.", sentence_trans: "政府對非法賭博活動發起了嚴厲打擊。", synonyms: ["suppression"], phrases: ["crackdown on"] }] }] },
    { id: "c229", word: "Cracker", ipa: "/ˈkræk.ər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "薄脆餅乾", def_en: "a thin, crisp wafer", sentence: "Whole grain crackers are a healthier alternative to potato chips.", sentence_trans: "全麥餅乾是比洋芋片更健康的替代品。", synonyms: ["biscuit"], phrases: [] }] }] },
    { id: "c230", word: "Cram", ipa: "/kræm/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "死記硬背；塞滿", def_en: "study intensively over a short period", sentence: "Many students try to cram for their exams the night before.", sentence_trans: "許多學生試圖在考試前一晚死記硬背。", synonyms: ["study", "stuff"], phrases: ["cram school"] }] }] },
    { id: "c231", word: "Cramp", ipa: "/kræmp/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "抽筋", def_en: "painful involuntary contraction of a muscle", sentence: "Dehydration can often lead to muscle cramps in athletes.", sentence_trans: "脫水常導致運動員肌肉抽筋。", synonyms: ["spasm"], phrases: [] }] }] },
    { id: "c232", word: "Crater", ipa: "/ˈkreɪ.tər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "火山口；坑", def_en: "a large, bowl-shaped cavity in the ground", sentence: "The asteroid impact left a massive crater on the planet's surface.", sentence_trans: "小行星撞擊在行星表面留下了一個巨大的坑。", synonyms: ["hole"], phrases: [] }] }] },
    { id: "c233", word: "Credibility", ipa: "/ˌkred.əˈbɪl.ə.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "可信度", def_en: "the quality of being trusted", sentence: "The scandal severely damaged the politician's credibility with the public.", sentence_trans: "醜聞嚴重損害了該政治家在公眾中的可信度。", synonyms: ["trustworthiness"], phrases: ["lose credibility"] }] }] },
    { id: "c234", word: "Credible", ipa: "/ˈkred.ə.bəl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "可信的", def_en: "able to be believed", sentence: "The witness provided a credible account of the events.", sentence_trans: "證人對事件提供了可信的描述。", synonyms: ["believable", "plausible"], phrases: ["credible evidence"] }] }] },
    { id: "c235", word: "Creek", ipa: "/kriːk/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "小溪", def_en: "a stream or minor tributary", sentence: "The children enjoyed catching tadpoles in the shallow creek.", sentence_trans: "孩子們喜歡在淺溪裡抓蝌蚪。", synonyms: ["stream", "brook"], phrases: [] }] }] },
    { id: "c236", word: "Cripple", ipa: "/ˈkrɪp.əl/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "使殘廢；嚴重削弱", def_en: "cause severe disablement; damage seriously", sentence: "High inflation threatens to cripple the country's economy.", sentence_trans: "高通膨威脅要嚴重削弱該國的經濟。", synonyms: ["disable", "paralyze"], phrases: [] }] }] },
    { id: "c237", word: "Criterion", ipa: "/kraɪˈtɪə.ri.ən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "標準", def_en: "a principle or standard by which something may be judged", sentence: "Academic performance is a key criterion for university admission.", sentence_trans: "學業成績是大學錄取的關鍵標準。", synonyms: ["standard", "measure"], phrases: ["meet the criteria"] }] }] },
    { id: "c238", word: "Crocodile", ipa: "/ˈkrɒk.ə.daɪl/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "鱷魚", def_en: "a large predatory reptile", sentence: "Crocodiles are apex predators in their aquatic ecosystems.", sentence_trans: "鱷魚是其水生生態系統中的頂級掠食者。", synonyms: [], phrases: ["crocodile tears"] }] }] },
    { id: "c239", word: "Crossing", ipa: "/ˈkrɒs.ɪŋ/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "交叉口；穿越", def_en: "a place where roads cross", sentence: "Pedestrians should always use the designated zebra crossing.", sentence_trans: "行人應始終使用指定的斑馬線穿越。", synonyms: ["junction"], phrases: ["level crossing"] }] }] },
    { id: "c240", word: "Crucial", ipa: "/ˈkruː.ʃəl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "關鍵的", def_en: "decisive or critical", sentence: "Early intervention is crucial for the successful treatment of the disease.", sentence_trans: "早期干預對於成功治療該疾病至關重要。", synonyms: ["vital", "essential"], phrases: ["play a crucial role"] }] }] },
    { 
        id: "c241", word: "Crude", ipa: "/kruːd/", priority: 10, 
        meanings: [
            { pos: "adj.", items: [{ def_zh: "天然的；未加工的", def_en: "in a natural or raw state", sentence: "The country's economy relies heavily on the export of crude oil.", sentence_trans: "該國經濟嚴重依賴原油出口。", synonyms: ["raw", "unrefined"], phrases: ["crude oil"] }] },
            { pos: "adj.", items: [{ def_zh: "粗魯的", def_en: "vulgar", sentence: "His crude jokes offended many of the guests.", sentence_trans: "他粗魯的笑話冒犯了許多客人。", synonyms: ["vulgar", "coarse"], phrases: [] }] }
        ] 
    },
    { 
        id: "c242", word: "Cruise", ipa: "/kruːz/", priority: 10, 
        meanings: [
            { pos: "v.", items: [{ def_zh: "巡航；乘船遊覽", def_en: "sail about for pleasure", sentence: "We plan to cruise around the Caribbean islands next summer.", sentence_trans: "我們計劃明年夏天在加勒比海島嶼周圍巡遊。", synonyms: ["sail", "voyage"], phrases: [] }] },
            { pos: "n.", items: [{ def_zh: "郵輪旅行", def_en: "a sea voyage for pleasure", sentence: "They booked a luxury cruise to Alaska.", sentence_trans: "他們預訂了去阿拉斯加的豪華郵輪旅行。", synonyms: [], phrases: [] }] }
        ] 
    },
    { id: "c243", word: "Crutch", ipa: "/krʌtʃ/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "拐杖；支撐物", def_en: "a support used by an injured person", sentence: "He had to walk on crutches for six weeks after breaking his leg.", sentence_trans: "他摔斷腿後不得不拄拐杖走了六週。", synonyms: ["support"], phrases: [] }] }] },
    { id: "c244", word: "Crystal", ipa: "/ˈkrɪs.təl/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "水晶", def_en: "a clear, transparent mineral", sentence: "The chandelier was made of high-quality crystal.", sentence_trans: "這盞吊燈是由高品質的水晶製成的。", synonyms: [], phrases: ["crystal clear"] }] }] },
    { id: "c245", word: "Cub", ipa: "/kʌb/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "幼獸", def_en: "the young of a fox, bear, lion, etc.", sentence: "The mother bear fiercely protected her cubs.", sentence_trans: "母熊猛烈地保護她的幼崽。", synonyms: [], phrases: [] }] }] },
    { id: "c246", word: "Cucumber", ipa: "/ˈkjuː.kʌm.bər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "黃瓜", def_en: "a long green vegetable", sentence: "Cucumber is a refreshing ingredient in summer salads.", sentence_trans: "黃瓜是夏季沙拉中清爽的食材。", synonyms: [], phrases: ["cool as a cucumber"] }] }] },
    { id: "c247", word: "Cuisine", ipa: "/kwɪˈziːn/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "料理；烹飪", def_en: "a style of cooking", sentence: "French cuisine is renowned worldwide for its sophistication and flavor.", sentence_trans: "法國料理以其精緻和風味聞名於世。", synonyms: ["cooking"], phrases: ["local cuisine"] }] }] },
    { id: "c248", word: "Cultivate", ipa: "/ˈkʌl.tɪ.veɪt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "培養；耕作", def_en: "try to acquire or develop", sentence: "The school aims to cultivate leadership skills in its students.", sentence_trans: "學校旨在培養學生的領導技能。", synonyms: ["foster", "nurture"], phrases: ["cultivate a habit"] }] }] },
    { id: "c249", word: "Cumulative", ipa: "/ˈkjuː.mjə.lə.tɪv/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "累積的", def_en: "increasing by successive additions", sentence: "The cumulative effect of human activity on the environment is alarming.", sentence_trans: "人類活動對環境的累積效應令人擔憂。", synonyms: ["accumulated"], phrases: ["cumulative effect"] }] }] },
    { 
        id: "c250", word: "Curb", ipa: "/kɜːb/", priority: 10, 
        meanings: [
            { pos: "v.", items: [{ def_zh: "抑制；控制", def_en: "restrain or keep in check", sentence: "The government raised interest rates to curb inflation.", sentence_trans: "政府提高利率以抑制通膨。", synonyms: ["control", "limit"], phrases: ["curb spending"] }] },
            { pos: "n.", items: [{ def_zh: "路緣", def_en: "edge of a sidewalk", sentence: "He parked his car close to the curb.", sentence_trans: "他把車停在靠近路緣的地方。", synonyms: [], phrases: [] }] }
        ] 
    },
    { id: "c251", word: "Curfew", ipa: "/ˈkɜː.fjuː/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "宵禁", def_en: "a regulation requiring people to remain indoors", sentence: "The military imposed a strict dusk-to-dawn curfew.", sentence_trans: "軍方實施了嚴格的黃昏到黎明的宵禁。", synonyms: [], phrases: ["impose a curfew"] }] }] },
    { id: "c252", word: "Currency", ipa: "/ˈkʌr.ən.si/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "貨幣", def_en: "a system of money", sentence: "The fluctuating value of the local currency has impacted tourism.", sentence_trans: "當地貨幣價值的波動影響了旅遊業。", synonyms: ["money"], phrases: ["foreign currency"] }] }] },
    { id: "c253", word: "Curriculum", ipa: "/kəˈrɪk.jə.ləm/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "課程", def_en: "subjects comprising a course of study", sentence: "The school curriculum includes a balance of arts and sciences.", sentence_trans: "學校課程包括藝術與科學的平衡。", synonyms: ["syllabus"], phrases: ["national curriculum"] }] }] },
    { 
        id: "c254", word: "Curry", ipa: "/ˈkʌr.i/", priority: 10, 
        meanings: [
            { pos: "n.", items: [{ def_zh: "咖哩", def_en: "a dish with strong spices", sentence: "We ordered a spicy chicken curry for dinner.", sentence_trans: "我們晚餐點了辣咖哩雞。", synonyms: [], phrases: [] }] },
            { pos: "v.", items: [{ def_zh: "討好", def_en: "ingratiate oneself", sentence: "He tried to curry favor with the boss by working late.", sentence_trans: "他試圖透過加班來討好老闆。", synonyms: [], phrases: ["curry favor"] }] }
        ] 
    },
    { id: "c255", word: "Custody", ipa: "/ˈkʌs.tə.di/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "監護權；拘留", def_en: "protective care or guardianship", sentence: "The court granted the mother full custody of the children.", sentence_trans: "法院判給母親對孩子的完全監護權。", synonyms: ["care", "guardianship"], phrases: ["in police custody"] }] }] },
    { id: "c256", word: "Customary", ipa: "/ˈkʌs.tə.mər.i/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "慣常的；習俗的", def_en: "according to custom", sentence: "It is customary to remove one's shoes before entering a Japanese home.", sentence_trans: "進入日本家庭前脫鞋是慣例。", synonyms: ["traditional", "usual"], phrases: [] }] }] },
    { id: "c257", word: "Customs", ipa: "/ˈkʌs.təmz/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "海關", def_en: "authority controlling imports", sentence: "All international passengers must pass through customs.", sentence_trans: "所有國際旅客都必須通過海關。", synonyms: [], phrases: ["customs officer"] }] }] },
    { id: "c258", word: "Cynical", ipa: "/ˈsɪn.ɪ.kəl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "憤世嫉俗的", def_en: "distrustful of human sincerity", sentence: "Years of political corruption have made the public cynical about the government.", sentence_trans: "多年的政治腐敗讓公眾對政府變得憤世嫉俗。", synonyms: ["skeptical", "distrustful"], phrases: ["cynical attitude"] }] }] }
]);