// =================================================================================
// 📚 雅思單字資料庫 - E 完整高階版 (Complete & High Quality E-List)
// =================================================================================
// 範圍：Eccentric (古怪的) ~ Eyesight (視力)
// 特色：包含多重詞性 (N/V/ADJ)、雅思學術例句、同義詞、片語

window.VOCAB_LIBRARY = window.VOCAB_LIBRARY || [];
window.VOCAB_LIBRARY = window.VOCAB_LIBRARY.concat([
    // --- E1: Eccentric to Entity ---
    { 
        id: "e001", word: "Eccentric", ipa: "/ɪkˈsen.trɪk/", priority: 10, 
        meanings: [{ pos: "adj.", items: [{ def_zh: "古怪的；反常的", def_en: "unconventional and slightly strange", sentence: "The professor was known for his eccentric habit of wearing mismatched socks to lectures.", sentence_trans: "這位教授因上課穿不成對襪子的古怪習慣而聞名。", synonyms: ["unconventional", "peculiar", "idiosyncratic"], phrases: ["eccentric behavior"] }] }] 
    },
    { 
        id: "e002", word: "Eclipse", ipa: "/ɪˈklɪps/", priority: 10, 
        meanings: [
            { pos: "n.", items: [{ def_zh: "日蝕；月蝕；黯然失色", def_en: "an obscuring of the light from one celestial body by the passage of another", sentence: "The total solar eclipse drew astronomers from around the world to the observation site.", sentence_trans: "日全蝕吸引了來自世界各地的天文學家前往觀測點。", synonyms: ["shadowing"], phrases: ["solar eclipse", "lunar eclipse"] }] },
            { pos: "v.", items: [{ def_zh: "使黯然失色；遮蔽", def_en: "deprive (someone or something) of significance, power, or prominence", sentence: "Her recent achievements have eclipsed the successes of her predecessors.", sentence_trans: "她最近的成就使前輩的成功黯然失色。", synonyms: ["overshadow", "outshine"], phrases: [] }] }
        ] 
    },
    { 
        id: "e003", word: "Ecological", ipa: "/ˌiː.kəˈlɒdʒ.ɪ.kəl/", priority: 10, 
        meanings: [{ pos: "adj.", items: [{ def_zh: "生態的", def_en: "relating to or concerned with the relation of living organisms to one another and to their physical surroundings", sentence: "The destruction of the rainforest has caused an ecological disaster with global implications.", sentence_trans: "雨林的破壞造成了具有全球影響的生態災難。", synonyms: ["environmental", "biological"], phrases: ["ecological balance", "ecological footprint"] }] }] 
    },
    { id: "e004", word: "Ecology", ipa: "/iˈkɒl.ə.dʒi/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "生態學", def_en: "the branch of biology that deals with the relations of organisms to one another and to their physical surroundings", sentence: "Understanding the local ecology is essential for effective conservation efforts.", sentence_trans: "了解當地生態對於有效的保育工作至關重要。", synonyms: ["bionomics"], phrases: [] }] }] },
    { id: "e005", word: "Ecosystem", ipa: "/ˈiː.kəʊˌsɪs.təm/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "生態系統", def_en: "a biological community of interacting organisms and their physical environment", sentence: "Coral reefs are fragile ecosystems that are highly sensitive to temperature changes.", sentence_trans: "珊瑚礁是脆弱的生態系統，對溫度變化高度敏感。", synonyms: ["environment"], phrases: ["marine ecosystem"] }] }] },
    { id: "e006", word: "Edible", ipa: "/ˈed.ɪ.bəl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "可食用的", def_en: "fit to be eaten", sentence: "Many wild mushrooms are not edible and can be highly toxic if ingested.", sentence_trans: "許多野生蘑菇不可食用，如果攝入可能會劇毒。", synonyms: ["safe to eat", "palatable"], phrases: ["edible oil"] }] }] },
    { id: "e007", word: "Editorial", ipa: "/ˌed.ɪˈtɔː.ri.əl/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "社論", def_en: "a newspaper article written by or on behalf of an editor that gives an opinion on a topical issue", sentence: "The newspaper published a controversial editorial criticizing the government's economic policy.", sentence_trans: "該報發表了一篇有爭議的社論，批評政府的經濟政策。", synonyms: ["article", "opinion piece"], phrases: ["editorial board"] }] }] },
    { id: "e008", word: "Ego", ipa: "/ˈiː.ɡəʊ/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "自我；自尊", def_en: "a person's sense of self-esteem or self-importance", sentence: "His massive ego prevented him from admitting that he had made a mistake.", sentence_trans: "他巨大的自尊心使他無法承認自己犯了錯。", synonyms: ["self-esteem", "self-importance"], phrases: ["boost one's ego"] }] }] },
    { 
        id: "e009", word: "Elaborate", ipa: "/iˈlæb.ər.ət/", priority: 10, 
        meanings: [
            { pos: "adj.", items: [{ def_zh: "精心製作的；詳盡的", def_en: "involving many carefully arranged parts or details", sentence: "The detectives uncovered an elaborate plot to defraud the insurance company.", sentence_trans: "偵探們揭露了一個精心策劃的詐騙保險公司的陰謀。", synonyms: ["intricate", "complex", "detailed"], phrases: [] }] },
            { pos: "v.", items: [{ def_zh: "詳細說明", def_en: "develop or present (a theory, policy, or system) in detail", sentence: "The minister declined to elaborate on the details of the new tax proposal.", sentence_trans: "部長拒絕詳細說明新稅收提案的細節。", synonyms: ["expand on", "flesh out"], phrases: ["elaborate on"] }] }
        ] 
    },
    { id: "e010", word: "Electrician", ipa: "/ɪˌlekˈtrɪʃ.ən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "電工", def_en: "a person who installs and maintains electrical equipment", sentence: "We need to hire a certified electrician to rewire the old house.", sentence_trans: "我們需要僱用一名合格的電工來為這棟老房子重新布線。", synonyms: [], phrases: [] }] }] },
    { id: "e011", word: "Elevate", ipa: "/ˈel.ɪ.veɪt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "提升；舉起", def_en: "raise or lift (something) up to a higher position", sentence: "The new policy aims to elevate the standard of living for low-income families.", sentence_trans: "新政策旨在提升低收入家庭的生活水準。", synonyms: ["raise", "lift", "upgrade"], phrases: ["elevate status"] }] }] },
    { id: "e012", word: "Eligible", ipa: "/ˈel.ɪ.dʒə.bəl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "有資格的；合適的", def_en: "having the right to do or obtain something", sentence: "Only citizens over the age of 18 are eligible to vote in the national election.", sentence_trans: "只有年滿18歲的公民才有資格在全國選舉中投票。", synonyms: ["qualified", "entitled"], phrases: ["eligible for"] }] }] },
    { id: "e013", word: "Elite", ipa: "/iˈliːt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "精英", def_en: "a select group that is superior in terms of ability or qualities", sentence: "The university is known for educating the country's political and business elite.", sentence_trans: "這所大學以教育該國的政治和商業精英而聞名。", synonyms: ["best", "cream of the crop"], phrases: ["elite forces"] }] }] },
    { id: "e014", word: "Eloquent", ipa: "/ˈel.ə.kwənt/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "雄辯的；有說服力的", def_en: "fluent or persuasive in speaking or writing", sentence: "She delivered an eloquent speech that moved the audience to tears.", sentence_trans: "她發表了一場雄辯的演講，感動得觀眾落淚。", synonyms: ["articulate", "persuasive", "expressive"], phrases: ["eloquent speaker"] }] }] },
    { 
        id: "e015", word: "Embrace", ipa: "/ɪmˈbreɪs/", priority: 10, 
        meanings: [
            { pos: "v.", items: [{ def_zh: "擁抱；欣然接受", def_en: "hold (someone) closely in one's arms; accept or support (a belief, theory, or change) willingly", sentence: "The company has decided to embrace new technologies to stay competitive.", sentence_trans: "公司已決定欣然接受新技術以保持競爭力。", synonyms: ["hug", "accept", "adopt"], phrases: ["embrace change"] }] },
            { pos: "n.", items: [{ def_zh: "擁抱", def_en: "an act of holding someone closely in one's arms", sentence: "He greeted his brother with a warm embrace.", sentence_trans: "他用溫暖的擁抱迎接他的兄弟。", synonyms: ["hug"], phrases: [] }] }
        ] 
    },
    { id: "e016", word: "Emigrant", ipa: "/ˈem.ɪ.ɡrənt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "移居國外者", def_en: "a person who leaves their own country in order to settle permanently in another", sentence: "The museum tells the stories of European emigrants who sought a new life in America.", sentence_trans: "這座博物館講述了尋求在美國新生活的歐洲移民的故事。", synonyms: ["migrant", "expatriate"], phrases: [] }] }] },
    { id: "e017", word: "Emigrate", ipa: "/ˈem.ɪ.ɡreɪt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "移居國外", def_en: "leave one's own country in order to settle permanently in another", sentence: "Many people emigrated from Ireland during the famine.", sentence_trans: "許多人在饑荒期間移居國外離開愛爾蘭。", synonyms: ["migrate", "relocate"], phrases: ["emigrate to"] }] }] },
    { id: "e018", word: "Emigration", ipa: "/ˌem.ɪˈɡreɪ.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "移居國外", def_en: "the act of leaving one's own country to settle permanently in another", sentence: "Mass emigration has led to a brain drain in the developing nation.", sentence_trans: "大規模的移居國外導致了這個發展中國家的人才外流。", synonyms: ["migration", "departure"], phrases: [] }] }] },
    { id: "e019", word: "Emission", ipa: "/iˈmɪʃ.ən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "排放；排放物", def_en: "the production and discharge of something, especially gas or radiation", sentence: "The government has pledged to reduce carbon emissions by 50% by 2030.", sentence_trans: "政府已承諾在2030年前將碳排放量減少50%。", synonyms: ["discharge", "release", "outflow"], phrases: ["gas emissions"] }] }] },
    { id: "e020", word: "Enchant", ipa: "/ɪnˈtʃɑːnt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "使陶醉；施魔法", def_en: "fill (someone) with great delight; charm", sentence: "The audience was completely enchanted by the ballerina's graceful performance.", sentence_trans: "觀眾完全陶醉於芭蕾舞者優雅的表演中。", synonyms: ["captivate", "charm", "delight"], phrases: ["enchanted forest"] }] }] },
    { id: "e021", word: "Encyclopedia", ipa: "/ɪnˌsaɪ.kləˈpiː.di.ə/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "百科全書", def_en: "a book or set of books giving information on many subjects", sentence: "Before the internet, the encyclopedia was the primary source of general knowledge.", sentence_trans: "在網際網路之前，百科全書是一般知識的主要來源。", synonyms: [], phrases: [] }] }] },
    { 
        id: "e022", word: "Endeavor", ipa: "/ɪnˈdev.ər/", 
        meanings: [
            { pos: "v.", items: [{ def_zh: "努力；力圖", def_en: "try hard to do or achieve something", sentence: "We must endeavor to improve the quality of our customer service.", sentence_trans: "我們必須努力提高客戶服務的品質。", synonyms: ["strive", "attempt", "struggle"], phrases: [] }] },
            { pos: "n.", items: [{ def_zh: "努力；嘗試", def_en: "an attempt to achieve a goal", sentence: "Despite his best endeavors, the project failed to meet the deadline.", sentence_trans: "儘管他盡了最大努力，該專案仍未能趕上截止日期。", synonyms: ["attempt", "effort"], phrases: [] }] }
        ], priority: 10 
    },
    { id: "e023", word: "Endorse", ipa: "/ɪnˈdɔːs/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "背書；贊同", def_en: "declare one's public approval or support of", sentence: "The celebrity was paid millions to endorse the new sports drink.", sentence_trans: "這位名人獲得數百萬美元來代言這款新的運動飲料。", synonyms: ["support", "approve", "sanction"], phrases: ["endorse a product"] }] }] },
    { id: "e024", word: "Endorsement", ipa: "/ɪnˈdɔːs.mənt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "背書；支持", def_en: "an act of giving one's public approval or support to someone or something", sentence: "The candidate sought the endorsement of the influential labor union.", sentence_trans: "候選人尋求有影響力的工會的支持。", synonyms: ["support", "approval"], phrases: ["official endorsement"] }] }] },
    { id: "e025", word: "Endowment", ipa: "/ɪnˈdaʊ.mənt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "捐贈；天賦", def_en: "a quality or ability possessed or inherited by someone; money given to a college", sentence: "The university received a generous endowment to fund new research facilities.", sentence_trans: "大學收到了一筆慷慨的捐贈，用於資助新的研究設施。", synonyms: ["gift", "funding", "talent"], phrases: [] }] }] },
    { id: "e026", word: "Endurance", ipa: "/ɪnˈdʒʊə.rəns/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "耐力；持久力", def_en: "the fact or power of enduring an unpleasant or difficult process or situation without giving way", sentence: "Marathon running requires a high level of physical and mental endurance.", sentence_trans: "馬拉松跑步需要高水平的身心耐力。", synonyms: ["stamina", "perseverance"], phrases: ["endurance test"] }] }] },
    { id: "e027", word: "Enhance", ipa: "/ɪnˈhɑːns/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "提高；增強", def_en: "intensify, increase, or further improve the quality, value, or extent of", sentence: "The use of multimedia can significantly enhance the learning experience.", sentence_trans: "使用多媒體可以顯著增強學習體驗。", synonyms: ["improve", "boost", "augment"], phrases: ["enhance performance"] }] }] },
    { id: "e028", word: "Enhancement", ipa: "/ɪnˈhɑːns.mənt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "增強；提升", def_en: "an increase or improvement in quality, value, or extent", sentence: "The software update includes several enhancements to user security.", sentence_trans: "軟體更新包括對用戶安全性的幾項增強。", synonyms: ["improvement", "augmentation"], phrases: [] }] }] },
    { id: "e029", word: "Enlighten", ipa: "/ɪnˈlaɪ.tən/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "啟發；開導", def_en: "give (someone) greater knowledge and understanding about a subject or situation", sentence: "Could you please enlighten me on your plans for the future?", sentence_trans: "你能否啟發我一下你對未來的計劃？", synonyms: ["inform", "educate", "illuminate"], phrases: [] }] }] },
    { id: "e030", word: "Enlightenment", ipa: "/ɪnˈlaɪ.tən.mənt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "啟蒙；教化", def_en: "the action of enlightening or the state of being enlightened", sentence: "The Age of Enlightenment emphasized reason and individualism.", sentence_trans: "啟蒙時代強調理性和個人主義。", synonyms: ["insight", "understanding"], phrases: [] }] }] },
    { id: "e031", word: "Enrich", ipa: "/ɪnˈrɪtʃ/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "使豐富；充實", def_en: "improve or enhance the quality or value of", sentence: "Reading diverse literature can enrich your vocabulary and worldview.", sentence_trans: "閱讀多樣化的文學作品可以豐富你的詞彙量和世界觀。", synonyms: ["enhance", "improve"], phrases: ["enrich one's life"] }] }] },
    { id: "e032", word: "Enrichment", ipa: "/ɪnˈrɪtʃ.mənt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "豐富；充實", def_en: "the action of improving or enhancing the quality or value of something", sentence: "The school offers an enrichment program for gifted students.", sentence_trans: "學校為資優學生提供充實課程。", synonyms: ["enhancement", "improvement"], phrases: [] }] }] },
    { id: "e033", word: "Enroll", ipa: "/ɪnˈrəʊl/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "註冊；登記", def_en: "officially register as a member of an institution or a student on a course", sentence: "You need to enroll in the course before the semester begins.", sentence_trans: "你需要在學期開始前註冊這門課程。", synonyms: ["register", "sign up"], phrases: ["enroll in"] }] }] },
    { id: "e034", word: "Enrollment", ipa: "/ɪnˈrəʊl.mənt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "註冊；入學人數", def_en: "the action of enrolling or being enrolled", sentence: "Enrollment in online courses has surged during the pandemic.", sentence_trans: "疫情期間，線上課程的註冊人數激增。", synonyms: ["registration", "admission"], phrases: [] }] }] },
    { id: "e035", word: "Enterprise", ipa: "/ˈen.tə.praɪz/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "企業；事業心", def_en: "a project or undertaking, typically one that is difficult or requires effort", sentence: "The government is encouraging the development of small and medium-sized enterprises.", sentence_trans: "政府正在鼓勵中小型企業的發展。", synonyms: ["business", "company", "venture"], phrases: ["private enterprise"] }] }] },
    { id: "e036", word: "Enthusiastic", ipa: "/ɪnˌθjuː.ziˈæs.tɪk/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "熱情的；熱衷的", def_en: "having or showing intense and eager enjoyment, interest, or approval", sentence: "The team received an enthusiastic welcome from their fans.", sentence_trans: "球隊受到了球迷熱情的歡迎。", synonyms: ["eager", "keen", "passionate"], phrases: ["enthusiastic about"] }] }] },
    { id: "e037", word: "Entitle", ipa: "/ɪnˈtaɪ.təl/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "給予權利；給...題名", def_en: "give (someone) a legal right or a just claim to receive or do something", sentence: "This ticket entitles you to a free meal at the restaurant.", sentence_trans: "這張票使你有權在餐廳享用一頓免費餐點。", synonyms: ["qualify", "authorize"], phrases: ["be entitled to"] }] }] },
    { id: "e038", word: "Entity", ipa: "/ˈen.tɪ.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "實體；存在", def_en: "a thing with distinct and independent existence", sentence: "The corporation is regarded as a separate legal entity from its owners.", sentence_trans: "該公司被視為與其所有者分開的獨立法律實體。", synonyms: ["body", "organization", "being"], phrases: [] }] }] },
    { id: "e039", word: "Entrepreneur", ipa: "/ˌɒn.trə.prəˈnɜːr/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "企業家", def_en: "a person who organizes and operates a business or businesses, taking on greater than normal financial risks", sentence: "The successful entrepreneur shared her insights on starting a business from scratch.", sentence_trans: "這位成功的企業家分享了她白手起家的見解。", synonyms: ["businessperson", "founder"], phrases: [] }] }] },
    { id: "e040", word: "Envious", ipa: "/ˈen.vi.əs/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "嫉妒的；羨慕的", def_en: "feeling or showing envy", sentence: "She was envious of her sister's success.", sentence_trans: "她嫉妒她姐姐的成功。", synonyms: ["jealous", "covetous"], phrases: ["envious of"] }] }] },
    { id: "e041", word: "Envision", ipa: "/ɪnˈvɪʒ.ən/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "想像；展望", def_en: "imagine as a future possibility; visualize", sentence: "The architect envisioned a modern building that would blend with nature.", sentence_trans: "建築師想像了一座能與自然融合的現代建築。", synonyms: ["visualize", "imagine", "foresee"], phrases: [] }] }] },

    // --- E2: Epidemic to Excessive ---
    { id: "e042", word: "Epidemic", ipa: "/ˌep.ɪˈdem.ɪk/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "流行病；蔓延", def_en: "a widespread occurrence of an infectious disease in a community", sentence: "The health authorities are working to contain the flu epidemic.", sentence_trans: "衛生當局正在努力遏制流感疫情。", synonyms: ["outbreak", "plague"], phrases: ["opioid epidemic"] }] }] },
    { id: "e043", word: "Episode", ipa: "/ˈep.ɪ.səʊd/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "插曲；一集", def_en: "an event or a group of events occurring as part of a larger sequence", sentence: "This was just one unfortunate episode in a long history of conflict.", sentence_trans: "這只是漫長衝突歷史中一個不幸的插曲。", synonyms: ["incident", "event", "chapter"], phrases: ["TV episode"] }] }] },
    { id: "e044", word: "Equalize", ipa: "/ˈiː.kwə.laɪz/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "使相等；使平等", def_en: "make the same in quantity, size, or degree throughout a place or group", sentence: "The government introduced measures to equalize opportunities for all citizens.", sentence_trans: "政府推出了使所有公民機會均等的措施。", synonyms: ["balance", "even out"], phrases: [] }] }] },
    { id: "e045", word: "Equate", ipa: "/ɪˈkweɪt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "同等看待；使相等", def_en: "consider (one thing) to be the same as or equivalent to another", sentence: "People often equate wealth with happiness, which is not always true.", sentence_trans: "人們常將財富與幸福畫上等號，這並不總是對的。", synonyms: ["identify", "liken"], phrases: ["equate to"] }] }] },
    { id: "e046", word: "Equation", ipa: "/ɪˈkweɪ.ʒən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "方程式；等式", def_en: "a mathematical statement that two mathematical expressions are equal", sentence: "Solving this complex equation requires advanced calculus skills.", sentence_trans: "解這個複雜的方程式需要進階微積分技能。", synonyms: [], phrases: ["mathematical equation"] }] }] },
    { id: "e047", word: "Equity", ipa: "/ˈek.wɪ.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "公平；股權", def_en: "the quality of being fair and impartial; the value of the shares issued by a company", sentence: "The education reform aims to promote equity in schools.", sentence_trans: "教育改革旨在促進學校的公平性。", synonyms: ["fairness", "justice"], phrases: ["private equity"] }] }] },
    { id: "e048", word: "Equivalent", ipa: "/ɪˈkwɪv.əl.ənt/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "相等的；等值的", def_en: "equal in value, amount, function, meaning, etc.", sentence: "One pound is roughly equivalent to 1.3 US dollars.", sentence_trans: "一英鎊大約等於 1.3 美元。", synonyms: ["equal", "identical", "comparable"], phrases: ["equivalent to"] }] }] },
    { 
        id: "e049", word: "Erect", ipa: "/ɪˈrekt/", priority: 10, 
        meanings: [
            { pos: "v.", items: [{ def_zh: "建立；豎立", def_en: "construct (a building, wall, or other upright structure)", sentence: "A monument was erected to honor the fallen soldiers.", sentence_trans: "豎立了一座紀念碑以紀念陣亡士兵。", synonyms: ["build", "construct"], phrases: [] }] },
            { pos: "adj.", items: [{ def_zh: "直立的", def_en: "rigidly upright or straight", sentence: "He stood erect with his shoulders back.", sentence_trans: "他挺直站立，肩膀向後。", synonyms: ["upright", "straight"], phrases: [] }] }
        ] 
    },
    { id: "e050", word: "Erection", ipa: "/ɪˈrek.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "建造；建築物", def_en: "the action of erecting a structure", sentence: "The erection of the new bridge will improve traffic flow.", sentence_trans: "新橋的建造將改善交通流量。", synonyms: ["construction", "assembly"], phrases: [] }] }] },
    { id: "e051", word: "Errand", ipa: "/ˈer.ənd/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "差事；跑腿", def_en: "a short journey undertaken in order to deliver or collect something", sentence: "I have a few errands to run before I can meet you.", sentence_trans: "在見你之前，我還有幾件差事要辦。", synonyms: ["chore", "task"], phrases: ["run errands"] }] }] },
    { id: "e052", word: "Erupt", ipa: "/ɪˈrʌpt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "爆發；噴發", def_en: "(of a volcano) become active and eject lava, ash, and gases", sentence: "The volcano could erupt at any moment, threatening nearby villages.", sentence_trans: "火山可能隨時噴發，威脅附近的村莊。", synonyms: ["explode", "burst"], phrases: ["erupt in laughter"] }] }] },
    { id: "e053", word: "Escalate", ipa: "/ˈes.kə.leɪt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "升級；惡化", def_en: "increase rapidly", sentence: "The conflict could escalate into a full-scale war if diplomacy fails.", sentence_trans: "如果外交失敗，衝突可能會升級為全面戰爭。", synonyms: ["intensify", "worsen", "rise"], phrases: ["escalate tensions"] }] }] },
    { id: "e054", word: "Escalator", ipa: "/ˈes.kə.leɪ.tər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "手扶梯", def_en: "a moving staircase", sentence: "The escalator in the subway station is out of order.", sentence_trans: "地鐵站的手扶梯壞了。", synonyms: [], phrases: [] }] }] },
    { 
        id: "e055", word: "Escort", ipa: "/ˈes.kɔːt/", priority: 10, 
        meanings: [
            { pos: "n.", items: [{ def_zh: "護送者", def_en: "a person, vehicle, or group accompanying another for protection", sentence: "The president traveled with a police escort.", sentence_trans: "總統在警察護送下出行。", synonyms: ["guard", "protector"], phrases: [] }] },
            { pos: "v.", items: [{ def_zh: "護送；陪同", def_en: "accompany (someone or something) somewhere", sentence: "Security guards escorted the celebrity to her car.", sentence_trans: "保全人員護送這位名人上車。", synonyms: ["accompany", "guide"], phrases: [] }] }
        ] 
    },
    { id: "e056", word: "Essence", ipa: "/ˈes.əns/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "本質；精髓", def_en: "the intrinsic nature or indispensable quality of something", sentence: "Freedom of speech is the very essence of democracy.", sentence_trans: "言論自由是民主的本質。", synonyms: ["core", "nature", "spirit"], phrases: ["of the essence"] }] }] },
    { id: "e057", word: "Estate", ipa: "/ɪˈsteɪt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "地產；財產", def_en: "an extensive area of land in the country, usually with a large house", sentence: "He inherited a large estate in the countryside from his grandfather.", sentence_trans: "他從祖父那裡繼承了鄉下的一大筆地產。", synonyms: ["property", "land", "assets"], phrases: ["real estate"] }] }] },
    { 
        id: "e058", word: "Esteem", ipa: "/ɪˈstiːm/", priority: 10, 
        meanings: [
            { pos: "n.", items: [{ def_zh: "尊敬；尊重", def_en: "respect and admiration", sentence: "She is held in high esteem by her colleagues.", sentence_trans: "她深受同事們的尊敬。", synonyms: ["respect", "admiration"], phrases: ["self-esteem"] }] },
            { pos: "v.", items: [{ def_zh: "尊敬；認為", def_en: "respect and admire", sentence: "I esteem his work highly.", sentence_trans: "我非常推崇他的工作。", synonyms: ["respect", "value"], phrases: [] }] }
        ] 
    },
    { id: "e059", word: "Eternal", ipa: "/ɪˈtɜː.nəl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "永恆的；不朽的", def_en: "lasting or existing forever; without end or beginning", sentence: "They swore eternal love to each other.", sentence_trans: "他們向對方發誓永恆的愛。", synonyms: ["everlasting", "perpetual", "endless"], phrases: ["eternal life"] }] }] },
    { id: "e060", word: "Eternity", ipa: "/ɪˈtɜː.nə.ti/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "永恆；漫長的時間", def_en: "infinite or unending time", sentence: "Waiting for the results felt like an eternity.", sentence_trans: "等待結果的過程感覺像過了一個世紀。", synonyms: ["infinity", "forever"], phrases: [] }] }] },
    { id: "e061", word: "Ethic", ipa: "/ˈeθ.ɪk/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "道德規範；倫理", def_en: "a set of moral principles", sentence: "The company promotes a strong work ethic among its employees.", sentence_trans: "公司在員工中提倡強烈的職業道德。", synonyms: ["moral", "principle"], phrases: ["work ethic"] }] }] },
    { id: "e062", word: "Ethical", ipa: "/ˈeθ.ɪ.kəl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "道德的；倫理的", def_en: "relating to moral principles", sentence: "The use of animals in cosmetic testing raises ethical questions.", sentence_trans: "在化妝品測試中使用動物引發了道德問題。", synonyms: ["moral", "principled"], phrases: ["ethical standard"] }] }] },
    { id: "e063", word: "Ethics", ipa: "/ˈeθ.ɪks/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "倫理學；道德標準", def_en: "moral principles that govern a person's behavior", sentence: "Medical ethics govern the behavior of doctors and nurses.", sentence_trans: "醫學倫理規範醫生和護士的行為。", synonyms: ["morality", "values"], phrases: ["code of ethics"] }] }] },
    { id: "e064", word: "Evacuate", ipa: "/ɪˈvæk.ju.eɪt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "撤離；疏散", def_en: "remove (someone) from a place of danger to a safer place", sentence: "Residents were ordered to evacuate the coastal areas as the hurricane approached.", sentence_trans: "隨著颶風逼近，居民被命令撤離沿海地區。", synonyms: ["remove", "clear", "vacate"], phrases: ["evacuate the building"] }] }] },
    { id: "e065", word: "Evergreen", ipa: "/ˈev.ə.ɡriːn/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "常綠的；歷久彌新的", def_en: "retaining green leaves throughout the year", sentence: "Pine trees are evergreen and stay green all winter.", sentence_trans: "松樹是常綠植物，整個冬天都保持綠色。", synonyms: [], phrases: ["evergreen content"] }] }] },
    { id: "e066", word: "Evoke", ipa: "/ɪˈvəʊk/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "喚起；引起", def_en: "bring or recall to the conscious mind", sentence: "The smell of freshly baked bread evoked memories of his childhood.", sentence_trans: "剛烤好的麵包香味喚起了他對童年的回憶。", synonyms: ["arouse", "elicit", "inspire"], phrases: ["evoke a response"] }] }] },
    { id: "e067", word: "Evolution", ipa: "/ˌiː.vəˈluː.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "演化；進化", def_en: "the process by which different kinds of living organisms are thought to have developed", sentence: "Darwin's theory of evolution changed our understanding of biology.", sentence_trans: "達爾文的演化論改變了我們對生物學的理解。", synonyms: ["development", "progression"], phrases: ["theory of evolution"] }] }] },
    { id: "e068", word: "Evolve", ipa: "/ɪˈvɒlv/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "演化；發展", def_en: "develop gradually", sentence: "The company has evolved from a small startup into a global corporation.", sentence_trans: "該公司已從一家小型初創企業發展成為全球性公司。", synonyms: ["develop", "progress"], phrases: ["evolve into"] }] }] },
    { id: "e069", word: "Exaggeration", ipa: "/ɪɡˌzædʒ.əˈreɪ.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "誇張；誇大", def_en: "a statement that represents something as better or worse than it really is", sentence: "It is no exaggeration to say that the internet has revolutionized communication.", sentence_trans: "毫不誇張地說，網際網路徹底改變了通訊。", synonyms: ["overstatement", "hyperbole"], phrases: ["gross exaggeration"] }] }] },
    { id: "e070", word: "Examinee", ipa: "/ɪɡˌzæm.ɪˈniː/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "應試者", def_en: "a person taking an examination", sentence: "Each examinee must present a valid ID before entering the exam hall.", sentence_trans: "每位應試者在進入考場前必須出示有效證件。", synonyms: ["candidate"], phrases: [] }] }] },
    { id: "e071", word: "Examiner", ipa: "/ɪɡˈzæm.ɪ.nər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "考官；審查員", def_en: "a person who sets and marks examinations", sentence: "The examiner asked the student to elaborate on his answer.", sentence_trans: "考官要求學生詳細說明他的答案。", synonyms: ["assessor", "inspector"], phrases: [] }] }] },
    { id: "e072", word: "Exceed", ipa: "/ɪkˈsiːd/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "超過；勝過", def_en: "be greater in number or size than", sentence: "The cost of the project is expected to exceed the initial budget.", sentence_trans: "該專案的成本預計將超過初始預算。", synonyms: ["surpass", "outstrip"], phrases: ["exceed expectations"] }] }] },
    { id: "e073", word: "Excel", ipa: "/ɪkˈsel/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "擅長；勝過", def_en: "be exceptionally good at or proficient in an activity or subject", sentence: "She has always excelled in mathematics and science.", sentence_trans: "她一直擅長數學和科學。", synonyms: ["shine", "stand out"], phrases: ["excel at"] }] }] },
    { id: "e074", word: "Exceptional", ipa: "/ɪkˈsep.ʃən.əl/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "卓越的；例外的", def_en: "unusually good; outstanding", sentence: "He showed exceptional talent for music at a very young age.", sentence_trans: "他在很小的時候就展現了卓越的音樂天賦。", synonyms: ["outstanding", "extraordinary"], phrases: ["exceptional circumstances"] }] }] },
    { 
        id: "e075", word: "Excerpt", ipa: "/ˈek.sɜːpt/", priority: 10, 
        meanings: [
            { pos: "n.", items: [{ def_zh: "摘錄；節錄", def_en: "a short extract from a film, broadcast, or piece of music or writing", sentence: "The teacher read a short excerpt from the novel to the class.", sentence_trans: "老師向全班朗讀了小說的一小段摘錄。", synonyms: ["extract", "snippet"], phrases: [] }] },
            { pos: "v.", items: [{ def_zh: "摘錄", def_en: "take a short extract from", sentence: "The article is excerpted from his latest book.", sentence_trans: "這篇文章摘錄自他的新書。", synonyms: ["quote", "extract"], phrases: [] }] }
        ] 
    },
    { 
        id: "e076", word: "Excess", ipa: "/ˈek.ses/", priority: 10, 
        meanings: [
            { pos: "n.", items: [{ def_zh: "過量；過度", def_en: "an amount of something that is more than necessary", sentence: "An excess of stress can lead to serious health problems.", sentence_trans: "過度的壓力會導致嚴重的健康問題。", synonyms: ["surplus", "glut"], phrases: ["in excess of"] }] },
            { pos: "adj.", items: [{ def_zh: "額外的；過量的", def_en: "exceeding a prescribed or desirable amount", sentence: "You will have to pay for any excess baggage.", sentence_trans: "你必須為任何超重的行李付費。", synonyms: ["extra"], phrases: ["excess baggage"] }] }
        ] 
    },
    { id: "e077", word: "Excessive", ipa: "/ɪkˈses.ɪv/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "過度的；極端的", def_en: "more than is necessary, normal, or desirable", sentence: "Excessive alcohol consumption is a major cause of liver disease.", sentence_trans: "過量飲酒是肝病的主要原因。", synonyms: ["immoderate", "extravagant"], phrases: ["excessive force"] }] }] },

    // --- E3: Exclaim to Eyesight (From Image 5) ---
    { id: "e078", word: "Exclaim", ipa: "/ɪkˈskleɪm/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "驚叫；呼喊", def_en: "cry out suddenly", sentence: "She exclaimed in delight when she saw the present.", sentence_trans: "當她看到禮物時，高興地驚叫起來。", synonyms: ["cry out", "shout"], phrases: [] }] }] },
    { id: "e079", word: "Exclude", ipa: "/ɪkˈskluːd/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "排除；不包括", def_en: "deny access to; keep out", sentence: "The club's rules exclude anyone under the age of 18.", sentence_trans: "俱樂部的規則排除了任何未滿18歲的人。", synonyms: ["bar", "ban", "omit"], phrases: ["exclude from"] }] }] },
    { id: "e080", word: "Excluding", ipa: "/ɪkˈskluː.dɪŋ/", priority: 10, meanings: [{ pos: "prep.", items: [{ def_zh: "不包括；除...之外", def_en: "not taking into account", sentence: "The price is $50, excluding tax.", sentence_trans: "價格是50美元，不含稅。", synonyms: ["except", "apart from"], phrases: [] }] }] },
    { id: "e081", word: "Exclusion", ipa: "/ɪkˈskluː.ʒən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "排除；排斥", def_en: "the process of excluding", sentence: "Social exclusion can lead to feelings of isolation and depression.", sentence_trans: "社會排斥會導致孤立和憂鬱感。", synonyms: ["omission", "barring"], phrases: ["to the exclusion of"] }] }] },
    { id: "e082", word: "Exclusive", ipa: "/ɪkˈskluː.sɪv/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "獨家的；排他的", def_en: "restricted to a particular person or group", sentence: "The magazine published an exclusive interview with the prime minister.", sentence_trans: "該雜誌刊登了對總理的獨家採訪。", synonyms: ["select", "private"], phrases: ["exclusive rights"] }] }] },
    { id: "e083", word: "Execute", ipa: "/ˈek.sɪ.kjuːt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "執行；處決", def_en: "carry out a plan; carry out a death sentence", sentence: "The company failed to execute its business strategy effectively.", sentence_trans: "該公司未能有效執行其商業策略。", synonyms: ["perform", "implement"], phrases: ["execute a plan"] }] }] },
    { id: "e084", word: "Execution", ipa: "/ˌek.sɪˈkjuː.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "執行；處決", def_en: "the carrying out of a plan; the carrying out of a death sentence", sentence: "The execution of the project was flawless.", sentence_trans: "該專案的執行完美無瑕。", synonyms: ["implementation", "performance"], phrases: ["put into execution"] }] }] },
    { 
        id: "e085", word: "Executive", ipa: "/ɪɡˈzek.jə.tɪv/", priority: 10, 
        meanings: [
            { pos: "n.", items: [{ def_zh: "主管；行政官", def_en: "a person with senior managerial responsibility", sentence: "Top executives met to discuss the merger.", sentence_trans: "高層主管開會討論合併事宜。", synonyms: ["manager", "director"], phrases: ["chief executive"] }] },
            { pos: "adj.", items: [{ def_zh: "行政的；執行的", def_en: "having the power to put plans into effect", sentence: "The president holds executive power.", sentence_trans: "總統握有行政權。", synonyms: ["administrative"], phrases: ["executive decision"] }] }
        ] 
    },
    { 
        id: "e086", word: "Exempt", ipa: "/ɪɡˈzempt/", priority: 10, 
        meanings: [
            { pos: "v.", items: [{ def_zh: "豁免", def_en: "free from an obligation", sentence: "He was exempted from military service due to health reasons.", sentence_trans: "由於健康原因，他被免除兵役。", synonyms: ["excuse", "spare"], phrases: ["exempt from"] }] },
            { pos: "adj.", items: [{ def_zh: "被豁免的", def_en: "free from an obligation", sentence: "Charitable organizations are often exempt from tax.", sentence_trans: "慈善組織通常免稅。", synonyms: ["immune"], phrases: ["tax exempt"] }] }
        ] 
    },
    { id: "e087", word: "Exert", ipa: "/ɪɡˈzɜːt/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "運用；施加", def_en: "apply or bring to bear (force, influence, etc.)", sentence: "He exerted all his influence to get the bill passed.", sentence_trans: "他運用了所有的影響力來讓法案通過。", synonyms: ["apply", "exercise"], phrases: ["exert pressure"] }] }] },
    { 
        id: "e088", word: "Exile", ipa: "/ˈek.saɪl/", priority: 10, 
        meanings: [
            { pos: "n.", items: [{ def_zh: "流放；流亡者", def_en: "the state of being barred from one's native country", sentence: "He spent ten years in political exile.", sentence_trans: "他過了十年的政治流亡生活。", synonyms: ["banishment"], phrases: ["in exile"] }] },
            { pos: "v.", items: [{ def_zh: "流放", def_en: "expel from a country", sentence: "The dictator exiled his political opponents.", sentence_trans: "獨裁者流放了他的政治對手。", synonyms: ["banish", "deport"], phrases: [] }] }
        ] 
    },
    { id: "e089", word: "Exotic", ipa: "/ɪɡˈzɒt.ɪk/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "異國情調的", def_en: "originating in or characteristic of a distant foreign country", sentence: "She enjoys tasting exotic fruits from South America.", sentence_trans: "她喜歡品嚐來自南美洲的異國水果。", synonyms: ["foreign", "alien"], phrases: ["exotic species"] }] }] },
    { id: "e090", word: "Expedition", ipa: "/ˌek.spəˈdɪʃ.ən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "遠征；探險", def_en: "a journey undertaken by a group of people with a particular purpose", sentence: "The scientific expedition to Antarctica discovered new marine species.", sentence_trans: "前往南極洲的科學探險隊發現了新的海洋物種。", synonyms: ["journey", "voyage"], phrases: ["go on an expedition"] }] }] },
    { id: "e091", word: "Expenditure", ipa: "/ɪkˈspen.dɪ.tʃər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "支出；花費", def_en: "the action of spending funds", sentence: "The government has promised to increase expenditure on healthcare.", sentence_trans: "政府已承諾增加醫療保健的支出。", synonyms: ["spending", "outlay"], phrases: ["public expenditure"] }] }] },
    { id: "e092", word: "Expertise", ipa: "/ˌek.spɜːˈtiːz/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "專業知識；專長", def_en: "expert skill or knowledge in a particular field", sentence: "We need someone with technical expertise to solve this problem.", sentence_trans: "我們需要有技術專長的人來解決這個問題。", synonyms: ["skill", "proficiency"], phrases: ["area of expertise"] }] }] },
    { id: "e093", word: "Expiration", ipa: "/ˌek.spɪˈreɪ.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "期滿；終止", def_en: "the ending of the fixed period for which something is valid", sentence: "Check the expiration date on the milk carton before drinking it.", sentence_trans: "喝牛奶前檢查紙盒上的有效期限。", synonyms: ["expiry", "termination"], phrases: ["expiration date"] }] }] },
    { id: "e094", word: "Expire", ipa: "/ɪkˈspaɪər/", priority: 10, meanings: [{ pos: "v.", items: [{ def_zh: "到期；終止", def_en: "come to the end of the period of validity", sentence: "My passport is due to expire next month.", sentence_trans: "我的護照將於下個月到期。", synonyms: ["run out", "lapse"], phrases: [] }] }] },
    { id: "e095", word: "Explicit", ipa: "/ɪkˈsplɪs.ɪt/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "明確的；清楚的", def_en: "stated clearly and in detail, leaving no room for confusion", sentence: "The manager gave explicit instructions on how to handle the complaint.", sentence_trans: "經理對於如何處理投訴給出了明確的指示。", synonyms: ["clear", "plain", "straightforward"], phrases: ["explicit content"] }] }] },
    { 
        id: "e096", word: "Exploit", ipa: "/ɪkˈsplɔɪt/", priority: 10, 
        meanings: [
            { pos: "v.", items: [{ def_zh: "剝削；利用", def_en: "make full use of and derive benefit from; use unfairly", sentence: "Companies should not exploit their workers for profit.", sentence_trans: "公司不應為了利潤而剝削工人。", synonyms: ["utilize", "abuse"], phrases: ["exploit resources"] }] },
            { pos: "n.", items: [{ def_zh: "功績；英勇行為", def_en: "a bold or daring feat", sentence: "His military exploits became legendary.", sentence_trans: "他的軍事功績成為了傳奇。", synonyms: ["feat", "deed"], phrases: [] }] }
        ] 
    },
    { id: "e097", word: "Exploration", ipa: "/ˌek.spləˈreɪ.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "探索；探測", def_en: "the action of traveling in or through an area in order to learn about it", sentence: "Space exploration has expanded our understanding of the universe.", sentence_trans: "太空探索擴展了我們對宇宙的理解。", synonyms: ["investigation", "survey"], phrases: ["space exploration"] }] }] },
    { id: "e098", word: "Extension", ipa: "/ɪkˈsten.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "延伸；擴充；分機", def_en: "a part that is added to something to enlarge or prolong it", sentence: "The university is planning an extension to the library.", sentence_trans: "大學正計劃擴建圖書館。", synonyms: ["addition", "expansion"], phrases: ["deadline extension"] }] }] },
    { id: "e099", word: "Extensive", ipa: "/ɪkˈsten.sɪv/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "廣泛的；大量的", def_en: "covering or affecting a large area", sentence: "The fire caused extensive damage to the building.", sentence_trans: "火災對建築物造成了廣泛的損害。", synonyms: ["widespread", "comprehensive"], phrases: ["extensive research"] }] }] },
    { 
        id: "e100", word: "Exterior", ipa: "/ɪkˈstɪə.ri.ər/", priority: 10, 
        meanings: [
            { pos: "adj.", items: [{ def_zh: "外部的", def_en: "forming, situated on, or relating to the outside", sentence: "The exterior walls of the house need painting.", sentence_trans: "房子的外牆需要粉刷。", synonyms: ["outer", "outside"], phrases: [] }] },
            { pos: "n.", items: [{ def_zh: "外部；外觀", def_en: "the outer surface or structure", sentence: "The exterior of the car was damaged in the accident.", sentence_trans: "車子的外觀在事故中受損。", synonyms: ["outside", "surface"], phrases: [] }] }
        ] 
    },
    { 
        id: "e101", word: "External", ipa: "/ɪkˈstɜː.nəl/", priority: 10, 
        meanings: [
            { pos: "adj.", items: [{ def_zh: "外部的；外面的", def_en: "belonging to or forming the outer surface or structure", sentence: "This medicine is for external use only.", sentence_trans: "此藥僅供外用。", synonyms: ["outer", "outside"], phrases: ["external affairs"] }] }
        ] 
    },
    { id: "e102", word: "Extinct", ipa: "/ɪkˈstɪŋkt/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "滅絕的", def_en: "having no living members", sentence: "Dinosaurs became extinct millions of years ago.", sentence_trans: "恐龍在數百萬年前滅絕了。", synonyms: ["vanished", "gone"], phrases: ["become extinct"] }] }] },
    { id: "e103", word: "Extinction", ipa: "/ɪkˈstɪŋk.ʃən/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "滅絕", def_en: "the fact or process of a species becoming extinct", sentence: "Habitat loss is a major cause of species extinction.", sentence_trans: "棲息地喪失是物種滅絕的主要原因。", synonyms: ["dying out"], phrases: ["mass extinction"] }] }] },
    { id: "e104", word: "Extinguisher", ipa: "/ɪkˈstɪŋ.ɡwɪ.ʃər/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "滅火器", def_en: "a device that discharges a jet of water, foam, gas, or other material to extinguish a fire", sentence: "Make sure you know how to operate the fire extinguisher in case of emergency.", sentence_trans: "確保你知道如何在緊急情況下操作滅火器。", synonyms: [], phrases: ["fire extinguisher"] }] }] },
    { 
        id: "e105", word: "Extract", ipa: "/ɪkˈstrækt/", priority: 10, 
        meanings: [
            { pos: "v.", items: [{ def_zh: "提取；拔出", def_en: "remove or take out, especially by effort or force", sentence: "The dentist had to extract the decayed tooth.", sentence_trans: "牙醫不得不拔掉那顆蛀牙。", synonyms: ["remove", "pull out"], phrases: ["extract data"] }] },
            { pos: "n.", items: [{ def_zh: "摘錄；提取物", def_en: "a short passage taken from a piece of writing; a preparation containing the active ingredient of a substance", sentence: "Read this extract from the novel.", sentence_trans: "閱讀這段小說摘錄。", synonyms: ["excerpt"], phrases: ["vanilla extract"] }] }
        ] 
    },
    { id: "e106", word: "Extracurricular", ipa: "/ˌek.strə.kəˈrɪk.jə.lər/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "課外的", def_en: "pursued in addition to the normal course of study", sentence: "She participates in many extracurricular activities, such as debate and sports.", sentence_trans: "她參加許多課外活動，如辯論和體育。", synonyms: [], phrases: ["extracurricular activities"] }] }] },
    { id: "e107", word: "Extraordinary", ipa: "/ɪkˈstrɔː.dɪn.ər.i/", priority: 10, meanings: [{ pos: "adj.", items: [{ def_zh: "非凡的；特別的", def_en: "very unusual or remarkable", sentence: "She has an extraordinary talent for mathematics.", sentence_trans: "她擁有非凡的數學天賦。", synonyms: ["remarkable", "exceptional"], phrases: ["extraordinary rendition"] }] }] },
    { id: "e108", word: "Eyelash", ipa: "/ˈaɪ.læʃ/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "睫毛", def_en: "each of the short curved hairs growing on the edges of the eyelids", sentence: "She applied mascara to her eyelashes to make them look longer.", sentence_trans: "她塗了睫毛膏讓睫毛看起來更長。", synonyms: ["lash"], phrases: [] }] }] },
    { id: "e109", word: "Eyelid", ipa: "/ˈaɪ.lɪd/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "眼瞼", def_en: "each of the upper and lower folds of skin which cover the eye when closed", sentence: "Her eyelids felt heavy with fatigue.", sentence_trans: "她的眼瞼因疲勞而感到沉重。", synonyms: ["lid"], phrases: [] }] }] },
    { id: "e110", word: "Eyesight", ipa: "/ˈaɪ.saɪt/", priority: 10, meanings: [{ pos: "n.", items: [{ def_zh: "視力", def_en: "a person's ability to see", sentence: "Regular eye exams are important for maintaining good eyesight.", sentence_trans: "定期眼科檢查對於保持良好視力很重要。", synonyms: ["vision", "sight"], phrases: ["poor eyesight"] }] }] }
]);